### ISSUE TITLE
Override the language files

### ISSUE THREAD

**Issue by navasclavero** [understrap/understrap-child#103]
How can I override the language files in the child theme? I need to modify /languages/es_ES.po

Thanks!

**Comment by Thomas-A-Reinert** [comment]
Sorry, didn´t realize this issue. But came across the same problem recently. Solved it with one of the latest commits. Please download the latest release and tell me if the problem persists. 

Closing this issue, cos i´m sure it _is_ solved ;) Feel free to reopen.

**Comment by Thomas-A-Reinert** [comment]
Instructions: copy understrap.pot from `themes/understrap/languages/understrap.pot` to `themes/understrap-child/languages/` . Make your translations and save them with your language string (es_ES.po/.mo) for example). This file should now be loaded automatically if your site is set to spanish language.
