### ISSUE TITLE
Missing classes in child theme.css

### ISSUE THREAD

**Issue by NicholasRowe** [understrap/understrap-child#107]
I've noticed that there are mssing bootstrap classes in the child theme.css

https://github.com/holger1411/understrap-child/blob/master/css/child-theme.css

All of the offset-* classes seem to be missing in the child theme.

They are apparent in the parent themes stylersheet:
https://github.com/holger1411/understrap/blob/master/css/theme.css

**Comment by holger1411** [comment]
The parent theme already uses Bootstrap 4 Beta 2.
But there are problems with this version so I wait for the Bootstrap team to fix it.
So the child theme is currently on Beta 1...

**Comment by Thomas-A-Reinert** [comment]
As we´re now using BS 4.1 everything should be resolved.

Closing this issue due to now follow-ups for about half a year. Feel free to reopen if needed.
