### ISSUE TITLE
Can I use Scout app instead of Node.js, npm, Gulp, bowser etc?

### ISSUE THREAD

**Issue by Stonino82** [understrap/understrap-child#109]
Do I have to use all these things, or can I simply use something like Scout app?

If the answer is yes, what is the workflow? Should I delete some files before start? Do I have to change some setting? Where do I save my news SCSS / CSS, or can I use some of the files that are already in theme?

**Comment by holger1411** [comment]
Hi!
I never used Scout, so I can´t tell. 
But if it just compiles scss files into css it should work.

At the end the theme use a css file called theme.min.css from the /css folder. So you should direct the output to this folder and give it this name.

If Scout respects all SASS rules it *should* work...feel free to try it ...and let us know!

**Comment by Thomas-A-Reinert** [comment]
Never used scout but using "PrePros" as a workaround on a customers computer I can tell it works with any SCSS-processor. You just need to compile it to `./css/theme.min.css`.
