### ISSUE TITLE
Problem with child-theme.min.js

### ISSUE THREAD

**Issue by Stonino82** [understrap/understrap-child#110]
Hi,
trying to add my custom js I noticed that I have some problem with this file.
This was my workflow:
1) I placed my child-theme-custom.js in src/js/.
2) I modified Gulpfile.js, replacing this line: 
basePaths.dev + 'js/skip-link-focus-fix.js' 
into:
basePaths.dev + 'js/skip-link-focus-fix.js', 
basePaths.dev + 'js/child-theme-custom.js'
3) Run gulp watch
4) Paste my code in child-theme-custom.js

It seems that Gulp is working good, because everything I paste in new child-theme-custom.js, I can see it in child-theme.js; but looking for a reason why this code is not working I opened the child-theme.min.js and this file looks a bit strange.
I don't know JavaScript language (and apologizes for the follow description), but I opened it with Dreamweaver and I can see how, at some point almost in the middle of the file, it changes from colours to all white.
Also, I paste my jss code directly at the very top of child-theme.min.jss and it works, but if I paste at the end it doesn't work.

Can anybody help me? Thanks in advance..

**Comment by Stonino82** [comment]
Ups ok..
It seemes that is not working, this is what Terminal returns me when I run gulp scripts:

MacBook-Pro-di-Antonino:understrap-child-master Stonino$ gulp scripts
[15:54:53] Using gulpfile /Applications/MAMP/htdocs/antoninolattene.com/wp-content/themes/understrap-child-master/gulpfile.js
[15:54:53] Starting 'scripts'...
[15:54:53] Finished 'scripts' after 15 ms
MacBook-Pro-di-Antonino:understrap-child-master Stonino$

**Comment by axlright** [comment]
That looks like it ran and compiled the scripts. It's a one time command, not an ongoing "watch" like the Sass compiler.

Are your compiled js files updated after the `gulp scripts` ran?

This is the workflow I use. I don't put my custom scripts into the `src/js` directory because the `src` directory can get overwritten or modified by updates. I put all my custom scripts into a directory in the root of the child theme. In my case I call this directory `custom-scripts` but of course you could call it whatever you want. 

Then here is how I structure the `gulpfile.js`

```
    var scripts = [
       basePaths.dev + 'js/jquery.min.js',
        // Start - All BS4 stuff
        basePaths.dev + 'js/bootstrap4/bootstrap.js',
        // End - All BS4 stuff

        // Start - All Custom stuff
        basePaths.dev + '../custom-scripts/*.js',
        // End - All Custom stuff

        basePaths.dev + 'js/skip-link-focus-fix.js'

    ];
```

**Comment by Stonino82** [comment]
Ok, I'm following your workflow.
I just have to structure the gulpfile.js.
Should I replece this part with your code?
`// Run:
// gulp scripts.
// Uglifies and concat all JS files into one
gulp.task('scripts', function() {
    var scripts = [

        // Start - All BS4 stuff
        basePaths.dev + 'js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        basePaths.dev + 'js/skip-link-focus-fix.js',
		basePaths.dev + 'js/child-theme-custom.js'
    ];
  gulp.src(scripts)
    .pipe(concat('child-theme.min.js'))
    .pipe(uglify().on('error', function(e){
            console.log(e);
         }))
    .pipe(gulp.dest('./js/'));

  gulp.src(scripts)
    .pipe(concat('child-theme.js'))
    .pipe(gulp.dest('./js/'));
});

// Deleting any file inside the /src folder
gulp.task('clean-source', function () {
  return del(['src/**/*',]);
});`

**Comment by axlright** [comment]
I would replace only

```
    var scripts = [

        // Start - All BS4 stuff
        basePaths.dev + 'js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        basePaths.dev + 'js/skip-link-focus-fix.js',
		basePaths.dev + 'js/child-theme-custom.js'
    ];
```
with
```
    var scripts = [
       basePaths.dev + 'js/jquery.min.js',
        // Start - All BS4 stuff
        basePaths.dev + 'js/bootstrap4/bootstrap.js',
        // End - All BS4 stuff

        // Start - All Custom stuff
        basePaths.dev + '../custom-scripts/*.js',
        // End - All Custom stuff

        basePaths.dev + 'js/skip-link-focus-fix.js'

    ];
```

Then make a directory called `custom-scripts` at the root level / top level of your child theme then add any js scripts you want into that then any time you want to re-compile the js, run `gulp scripts`

**Comment by Stonino82** [comment]
I just run gulp scripts and it seems there is some error:
MacBook-Pro-di-Antonino:understrap-child-master Stonino$ gulp scripts
```
/Applications/MAMP/htdocs/antoninolattene.com/wp-content/themes/understrap-child-master/gulpfile.js:177
var scripts = [
^^^

SyntaxError: Unexpected token var
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
MacBook-Pro-di-Antonino:understrap-child-master Stonino$ 
```

**Comment by Stonino82** [comment]
Something is going wrong.
Now child-theme.js looks like minify at the top, and I don't see the new code in it.
In child-theme.min.js I do not see changes either.

**Comment by Stonino82** [comment]
Do I have to run gulp cripts every time I make a change in my custom scripts?

**Comment by Stonino82** [comment]
So I run gulp scripts after customize my custom scripts, and it is working.
But child-theme.js looks very strange, the first 5 line are minify and I don't know from where this code comes from.

**Comment by Stonino82** [comment]
I figured out that this code comes from the new line:
`basePaths.dev + 'js/jquery.min.js'`
and I change it into:
`basePaths.dev + 'js/jquery.js'`
as all of the others are not minify versions.
I don't know if it is correct..


Maybe the reason why it didn't work was just because I needed jquery.js inside the gulp.task in gulpfile.js

**Comment by Stonino82** [comment]
I am a little confused about the use of npm and the packages that I have installed.
I just installed a package for an animated scroll, and it's located inside node_modules. I do not understand if it is already correctly linked so that I can use it directly from its current location or if I have to put the js to my custom-scripts folder ..

In a few words: what to do after having installed a package through npm that we want to use?

**Comment by shansmith01** [comment]
This is what I have done.

- Add a package via npm
- Update my guplfile so the right files get loaded into my theme files in the right place. Eg -

`This is adding social media buttons
    gulp.src(basePaths.node + 'rrssb/js/rrssb.min.js')
        .pipe(gulp.dest(basePaths.dev + '/js/'));

    gulp.src(basePaths.node + 'rrssb/js/rrssb.js')
        .pipe(gulp.dest(basePaths.dev + '/js/'));

    gulp.src(basePaths.node + 'rrssb/scss/rrssb.scss')
        .pipe(rename('_rrssb.scss'))
        .pipe(gulp.dest('sass/theme/'))`

- Then i run gulp copy-assets, gulp scripts, gulp watch- This puts everything in it;s place
- Then I go ahead and use the package according to the instructions

**Comment by Thomas-A-Reinert** [comment]
Whole structure changed within parent/child. Never met that problem in the near past, so I´ll close that issue due to not being able to reproduce and no further comments within the last half year.

Feel free to re-open if needed.
