### ISSUE TITLE
child-theme.min.js error

### ISSUE THREAD

**Issue by Cybergo-at** [understrap/understrap-child#114]
Hi,

Currently, I'm working on a new theme using understrap child theme. I've updated understrap to 0.6.9.3, and now I'm getting an error in the console regarding child-theme.min.js:

![image](https://user-images.githubusercontent.com/15031319/33390939-1af03408-d540-11e7-8816-bc38b79be27c.png)

Also, I noticed that in the last version jQuery-slim was removed, and thus I removed it as well from functions.php

I guess we have to wait for a new version of the child theme to fix all last changes.

**Comment by tonbo** [comment]
<img width="550" alt="2017-12-01 3 58 23" src="https://user-images.githubusercontent.com/1910345/33449564-7f9bba64-d64c-11e7-9380-c2e5f470ee53.png">

I got almost same error on understrap 0.6.9.3 and child theme 0.3.9.

**Comment by shawncampbell** [comment]
I'm seeing similar results—jQuery isn't loading on the frontend—with understrap 0.6.9 and 0.6.10 while using understrap-child 0.3.9. As a temporary workaround, I downgraded back to 0.6.7.

**Comment by holger1411** [comment]
The strange thing is that Understrap 0.6.10 nor UnderStrap child 0.39 loads jQuery 3.2.1 anymore but uses the Wordpress core jQuery version.

Pls compare your child themes functions.php with the latest version here:
https://github.com/holger1411/understrap-child/blob/master/functions.php

@tonbo: You screenshot shows that you use the child theme v 0.3.6.
Pls update to 0.3.9
Instead of updating is completely (including loosing your changes...)
Just replace the package.json, functions.php and gulpfile.js from the new version.

**Comment by denislam** [comment]
I am using 0.3.9 with Understrap 0.6.09 and dropdowns are not working. Chrome console says "
child-theme.min.js?ver=0.3.9:1 Uncaught ReferenceError: jQuery is not defined." Tried 0.3.10 - same issue.

**Comment by eversionsystems** [comment]
Modify your gulpfile.js to include a version of jQuery

```
gulp.task('scripts', function() {
    var scripts = [

	basePaths.dev + 'js/jquery.min.js',
	
        // Start - All BS4 stuff
        basePaths.dev + 'js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        basePaths.dev + 'js/skip-link-focus-fix.js'
    ];
```

**Comment by shansmith01** [comment]
I also needed to add this to place this in my functions.php to include a version of Jquery

`wp_enqueue_script( 'querymin', get_stylesheet_directory_uri() . '/js/jquery.min.js','','', false );`

I was getting several other bugs before adding in a version of jquery. Wordpress' version was being loaded but as it was included in the footer and below other scripts I was adding It was causing issues.

Adding wp_enqueue_script( 'jquery' ); moved WP's jquery version to the top, and solved many issues but still did not fix the issues with the child-thme.js

Hope that's useful

**Comment by denislam** [comment]
@eversionsystems Thank you. I'd like to note that I would have to also add a copy of jquery.min.js in the ../src/js/ directory as well to get it to work.

**Comment by eversionsystems** [comment]
@denislam, it depends on what base path you are using in your script.

**Comment by denislam** [comment]
@eversionsystems You are correct. I was using and referring to the default base path assigned by the child theme:

```
// Defining base pathes
var basePaths = {
    js: './js/',
    node: './node_modules/',
    dev: './src/'
};
```

**Comment by Thomas-A-Reinert** [comment]
Should be resolved. Feel free to reopen if neccessary.
