### ISSUE TITLE
Current-menu-item class missing

### ISSUE THREAD

**Issue by Stonino82** [understrap/understrap-child#115]
I do not find this class on my menu, so I can not give it style. Why is this happening?
Also, I would like to know where the menu is registered? I do not see it in the Understrap parent file fuction. Do I have to register it?

**Comment by Thomas-A-Reinert** [comment]
The menu is registered in functions.php

`   63: require get_template_directory() . '/inc/bootstrap-wp-navwalker.php';`

The class is there - but it´s applied to it´s parent li: "current-menu-item". So you can easily access it via
`.current-menu-item a { .. }`

**Comment by Stonino82** [comment]
No, it is not applying the class to any <li> of the menu:

<li id="menu-item-1696" class="menu-item menu-item-type-custom menu-item-object-custom nav-item menu-item-1696"><a title="Contact" href="#contact" class="nav-link">Contact</a></li>

**Comment by Thomas-A-Reinert** [comment]
I can´t reproduce if this was really an issue at the time you asked - but i can promise that this has been resolved by now.
