### ISSUE TITLE
Problem with custom js

### ISSUE THREAD

**Issue by Stonino82** [understrap/understrap-child#120]
I still have some problems with the JS custom files.

I'm trying to use Isotope and ImagesLoaded in my project, but the code works only if I add it in the footer.

I usually put my custom scripts in custom-scripts / main.js, and then compile them using the "gulp scripts" command in the terminal, but this code does not seem to work.
Here you have the code, I hope you can help me out, because I can not understand what is the problem:

```
// Active isotope with jQuery code:
var $grid = $('.grid').imagesLoaded( function() {
  // init Isotope after all images have loaded
  $grid.isotope({
    itemSelector: '.grid-item',
    percentPosition: true,
    masonry: {
        // use outer width of grid-sizer for columnWidth
        columnWidth: '.grid-sizer'
    }
  });
});

// Isotope click function
$('.iso-nav a').click(function(){
  $('.iso-nav a').removeClass('active');
  $(this).addClass('active');

  var selector = $(this).attr('data-filter');
  $('.grid').isotope({
    filter: selector
  });
  return false;
});
```

**Comment by floppyTop** [comment]
I'm having the same issue here, and I compile mine in the same manner. I didn't have the issue until the most recent update.

**Some detail:**
jQuery is loading fine, originally it wasn't but then I revised my functions.php file to enqueue scripts in the same manner that is shown in the git code for understrap-child, and now that loads.

Once it loads, the error that is seemingly preventing the rest of my custom script, (particles.js) from loading is the following error:
```
Cannot read property 'fn' of undefined
    at child-theme.min.js?ver=0.3.6:formatted:86
```

When pretty-printing the script, this is the line it's being thrown on:
        ```
**e.fn.emulateTransitionEnd = n**,
        r.supportsTransitionEnd() && (e.event.special[r.TRANSITION_END] = {
            bindType: i.end,
            delegateType: i.end,
            handle: function(t) {
                if (e(t.target).is(this))
                    return t.handleObj.handler.apply(this, arguments)
            }
        })
```

Can you guys let me know if I'm doing something wrong here?

**Comment by eberhapa** [comment]
It an bootstrap beta issue (https://github.com/holger1411/understrap/issues/449). Should have been fixed in understrap 0.6.7 but still present for me in the child theme on version 0.3.10 as well.

**Comment by joelscampos** [comment]
In my case the problema was because I put the "bootstrap.min.js" before the "jquery-3.2.1.slim.min.js".
After I put the bootstrap after the jquery, the error disappeared.

**Comment by Thomas-A-Reinert** [comment]
Should´ve been solved by now. Using isotope successfully without any "dirty tricks" in one of my installations..

Feel free to reopen if the problem persists.
