### ISSUE TITLE
Fontawesome 4 conflicts with Fontawesome 5

### ISSUE THREAD

**Issue by jaredsnider** [understrap/understrap-child#126]
First of all, thank you for this amazing tool... it is super helpful and I appreciate it A LOT!

One thing I have run into is conflicts with Fontawesome 4 and 5. With both CSS files being referenced some of the FA4 stuff was overriding FA5

I "solved" it by commenting out the Fontawesome 4 SCSS import in the "assets" folder and installing Fontawesome 5 along with my other "custom" fonts in a separate folder (I haven't included the CSS in the gulpfile as I am not super saavy and its no big deal), which I will have to remember to do if I updated the child theme.

Not sure if eventually FA5 will be included in the Bootstrap defaults (and how "FA5 Pro" users will need to further implement beyond the "FA5 Free" implementation). Just a heads up for anyone who has a similar issue.

**Comment by axlright** [comment]
Nice one @jaredsnider! I've also replaced FontAwesome4 with FontAwesome5 in all my projects. I removed references to the @include for FontAwesome4 and in fact removed all the .scss and font files for FontAwesome4.

I'd love to be smart enough to figure out how to fully remove FontAwesome4 from the npm install workflow as I have to manually delete all the FontAwesome4 .scss and font files every time I update the child theme. But alas, I'm not that smart so I just manually remove them all.

**Comment by axlright** [comment]
@IngoVals Please refer to issue 574 in the parent theme repo issues tracker: https://github.com/understrap/understrap/issues/547

Unless you have issues here that aren't answered there, I'll close this ticket to not have duplicates. Yes, different repository but similar issue. Thanks!

**Comment by justme101** [comment]
4 and 5 are different as far as naming and styles. .fab is being used in place of .fa for some of the icons

**Comment by axlright** [comment]
Closing this issue as it's being tracked in the parent theme repo issue 574: understrap/understrap#547
