### ISSUE TITLE
making understarap/inc/bootstrap-wp-navwalker.php editable in child theme

### ISSUE THREAD

**Issue by coolclick** [understrap/understrap-child#133]
Not sure if this is the best place to request help.  I would like to edit the understrap/inc/bootstrap-wp-navwalker.php file inside my child theme (ie:  understrap-child/inc/bootstrap-wp-navwalker.php).  Just placing it here does not make it recognizable.  How can I do so?

Thank you,

**Comment by holger1411** [comment]
The parent theme loads this file via functions.php.
If you want to replace it within your child theme you have to overwrite this function in your child themes function.php.

Add the whole function starting with 👍 
`class understrap_WP_Bootstrap_Navwalker extends Walker_Nav_Menu {`


to your child themes function.php. Than do your changes there.

This call:
`if (! class_exists ( 'understrap_WP_Bootstrap_Navwalker' )) :`

ensures that the parent theme did not loads its own function if it is present in the child theme

**Comment by Thomas-A-Reinert** [comment]
Should´ve been solved with the latest version for almost any known function (hopefully).

So any function/class you meet within the parent theme can be overwritten within the child by just redefining it without an if exist clause. It will be loaded BEFORE the parent so if it has already been declared there, the `if (! class_exists ( 'understrap_WP_Bootstrap_Navwalker' ))` check within the parent will never become true and therefore execute ;)

Closing this topic as this didn´t get a reply within nearly a month and should be resolved anyway..

**Comment by cdsaenz** [comment]
Hi, I need to implement a multilevel Walker (one with level 3). I have a Walker class that I use in another WP theme that does it, I might implement it through this overriding you mention, but I saw the demo at https://demos.understrap.com/ and it already has a level 3.. Am I missing something or is that made with some other walker? (I'm trying to avoid adding my own code if the base theme already has it) Thanks!

**Comment by bacoords** [comment]
Hi, the base theme only goes to two levels in its navwalker. Funny enough, one of our developers a few years back was working on a method to offer the third level, and I guess it was actually left running on the demo site.

That said, I don't know that it was ever completed or audited for good accessibility.

**Comment by cdsaenz** [comment]
Yeah BootScore doesn't provide it out of the box either, and I understand because it's not Bootstrap style. Don't worry I've already integrated mine, thanks a lot!
