### ISSUE TITLE
How to change theme name and child theme setup question

### ISSUE THREAD

**Issue by DPUK44** [understrap/understrap-child#134]
Just started using Understand and built my first site using it. Love it! My 1st site theme name is Understrap, so on my next site I want to know what's the best way to change the name of the theme?

Cheers!

**Comment by birdm99** [comment]
Try to use child theme - it is the best practice. Then edit `style.css`  file. There are all infos about template, also the name of it.

**Comment by DPUK44** [comment]
In your instructions you mention to execute Run: $ npm install then: $ gulp copy-assets

But is this for the child folder only? or do you have to run in the main Understrap folder?

**Comment by DPUK44** [comment]
To anyone seeking the same answers these commands are to be run in the child folder

**Comment by IngoVals** [comment]
Seems solved, closing. Feel free to reopen if issue isn't resolved.
