### ISSUE TITLE
How to use a child theme

### ISSUE THREAD

**Issue by mherda** [understrap/understrap-child#136]
Apologies for a basic question, but I don't get the worflow of working with child themes. I understand that the reason for using them is to keep the parent theme intact and prevent any updates to the parent theme from overwriting your custom modifications. Now once you've downloaded a child theme, you only have a few files. What if you need to edit the files that are not originally present in the child theme (but are present in the parent, eg. template-parts / loops, etc.)?
Do you copy then copy them from the parent manually?

Thank you

**Comment by birdm99** [comment]
Yes exactly, just copy those files into child theme dir and edit them.

**Comment by mherda** [comment]
Aaah. ok. Thanks. What happens when I pull the latest updates of the parent theme from github and my child theme version of a file differs from the one in a newly updated parent theme? What happens then or what do I need to do then?

**Comment by birdm99** [comment]
Whole idea of child theme is that if you update parent theme child theme stays intact. So after all the child theme files will be loaded by WP and your changes wont be overwritten.

**Comment by mherda** [comment]
I understand that but what happens if the parent gets some bug fixes (that I would benefit from in the child theme) in the files I have modified in my child theme? Assuming I don't want to ignore the updates, do I git diff the files to identify what's changed and manually update my files to include the bug fixes?

**Comment by axlright** [comment]
>I understand that but what happens if the parent gets some bug fixes (that I would benefit from in the child theme) in the files I have modified in my child theme? Assuming I don't want to ignore the updates, do I git diff the files to identify what's changed and manually update my files to include the bug fixes?

Yes, pretty much. I've used the child theme on a dozen or so client projects, and it's not super common for updates to happen in the parent theme to files you've copied and customized in the child theme. But it does happen, especially with Bootstrap coming out of beta and whatnot.

**Comment by mherda** [comment]
OK. Thanks
