### ISSUE TITLE
TinyMCE missing padding

### ISSUE THREAD

**Issue by eberhapa** [understrap/understrap-child#139]
TinyMCE is missing padding. The text sticks to the top left. I managed it adding padding in custom editor styles for the 'tinymce' id. 
Question: How to remove the custom-editor-styles of the parent theme at all?

**Comment by holger1411** [comment]
Was fixed here:
https://github.com/understrap/understrap/commit/0640bf70946c35766978c1db1b9732853c78f6eb
and will be shipped with UnderStrap 0.8.2

For removing it as workaround remove the stylesheet call from inc/editor.php:

```
/**
 * Registers an editor stylesheet for the theme.
 */
function understrap_wpdocs_theme_add_editor_styles() {
  add_editor_style( 'css/custom-editor-style.min.css' );
}
add_action( 'admin_init', 'understrap_wpdocs_theme_add_editor_styles' );
```
