### ISSUE TITLE
update bootstrap (still using pull/push vs order)

### ISSUE THREAD

**Issue by uitta** [understrap/understrap-child#141]
Hello everybody.
Even though i updated everything, my child theme is still using a beta version of bootstrap.
It still use push/pull instead of order. 
How can i manage to update it? What am i missing?

**Comment by uitta** [comment]
Ok so....
i update the package.json, the assets file, and redone a npm install.
Everything(quite) is working well... am i doing the right thing or is there a faster/secure way, to update?

**Comment by axlright** [comment]
Hi @uitta - to update the child theme, you need to copy three files:
1) gulpconfig.json
2) gulpfile.js
3) package.json

Then run `npm update` and make sure `gulp copy-assets` was run. I'm not smart enough to know the difference between `npm update` and `npm install` so I often run `npm install` to be safe as that includes `gulp copy-assets`

Then run `gulp scripts` and `gulp styles` to make sure all the scripts and styles are compiled.

You may also want to manually update the child theme version number listed in `style.css` to match the version number listed in `package.json` but that is just cosmetic and doesn't really affect anything.

You don't need to copy the `assets` directory as that gets generated when `gulp copy-assets` gets run.

Let me know if this is helpful. The documentation needs an update.

**Comment by IngoVals** [comment]
I do believe `npm update` also updates already installed packages where allowed by the versioning mentioned in `package.json`.

**Comment by axlright** [comment]
Closing this ticket as it appears solved. Comment to re-open if issues persist.
