### ISSUE TITLE
How to load Flexslider CSS?

### ISSUE THREAD

**Issue by peterjrees** [understrap/understrap-child#147]
Hi there - first of all, thanks for making this awesome starter theme!

I'm attempting to install a Flexslider on my home page using the Understrap child theme. I seem to have it working but the default styles for the navigation controls etc are missing - I'm unsure how to go about loading the Flexslider stylesheet as there is no **.scss** file - only **.css** and **.less** files. I'm assuming I just need to add the path to one of these files in `gulpfile.js` somehow?

**For clarity, here's the steps I've taken to get to this point:**

I've run `npm install flexslider` and added the following Flexslider javascript in `src/js/custom.js`

```javascript
jQuery(window).load(function() {
    jQuery('.flexslider').flexslider({
        slideshowSpeed: "10000"
    });
});
```
_(Note that I've used `jQuery` instead of `$` due to getting the `$ is not a function` error - not sure if there's a way around this?)_

I've then added paths to the Flexslider js and my custom js file in `gulpfile.js` as follows:

```javascript
// Run:
// gulp scripts.
// Uglifies and concat all JS files into one
gulp.task('scripts', function() {
    var scripts = [

        // Start - All BS4 stuff
        basePaths.dev + 'js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        basePaths.dev + 'js/skip-link-focus-fix.js',

        basePaths.dev + 'js/jquery.flexslider-min.js',

        // Please add any customizations to this .js file only!
        basePaths.dev + 'js/custom.js'
    ];
```
Flexslider markup is in the Home Page template `page-templates/home.php` and looks something like this:

```html
<div class="flexslider">
  <ul class="slides">
    <li>
      <div class="flexslide">
        <div class="container">
          <div class="row">
            <div class="col-sm-6">
              <h1>Slide 1</h1>
              <a class="btn btn-lg btn-primary" href="#">Button 1</a>
            </div>
          </div>
        </div>
      </div>
    </li>
    <li>
      <div class="flexslide">
        <div class="container">
          <div class="row">
            <div class="col-sm-6">
              <h1>Slide 2</h1>
              <a class="btn btn-lg btn-primary" href="#">Button 2</a>
            </div>
          </div>
        </div>
      </div>
    </li>
  </ul>
</div>
```
I've run `gulp copy-assets` and `gulp scripts`. 

Being fairly new to NPM and Gulp I'm sure I've just missed something simple here and open to any suggestions on how to implement this better.

Thanks in advance!
Peter

**Comment by IngoVals** [comment]
I believe the jQuery instead of $ is intentional on behalf of Wordpress since many javascript libraries use $ and they want to minimize risk of conflict.

Do you get any error in the console for this?

I haven't looked into the enqueuing format enough but possibly it is about order of javascript being loaded.

`    wp_enqueue_style( 'child-understrap-styles', get_stylesheet_directory_uri() . '/css/child-theme.min.css', array(), $the_theme->get( 'Version' ) );
    wp_enqueue_script( 'jquery');`

Should perhaps be

`    wp_enqueue_style( 'child-understrap-styles', get_stylesheet_directory_uri() . '/css/child-theme.min.css', array('jquery'), $the_theme->get( 'Version' ) );`

**Comment by peterjrees** [comment]
Thanks for the reply @IngoVals - I'm not getting any console errors and the Flexslider script appears to be working.

It's actually the Flexslider CSS that I'm having trouble with as I'm not sure how best to compile it into the main `child-theme.min.css` stylesheet.

**Comment by axlright** [comment]
@peterjrees compiling additional css is easier - add it as an @include in your /sass/child_theme.scss - compiles regular css just like Sass. So just point to your css file and compile away.

**Comment by peterjrees** [comment]
Thanks @axlright that did the trick!
