### ISSUE TITLE
Left sidebar not showing

### ISSUE THREAD

**Issue by nuriye** [understrap/understrap-child#150]
I just downloaded the understrap theme & child theme and tried to add widgets to the left and right sidebar.
But only the ones in the right sidebar are showing in the frontend, even though I have set widgets in the left one with content (Text and Category, which are showing perfectly in the right sidebar).
In left-sidebar-check the variable $sidebar_pos has "right" in it.. this should be both?
It neither works in the parent nor in the child theme.

**Comment by holger1411** [comment]
Oh, and you can set it up on the page level individually be selecting a proper template. Which overwrites the default customizer setting.

**Comment by Thomas-A-Reinert** [comment]
I guess that one´s solved. At least in my test environment. And thus you didn´t respond within 3 weeks I´ll close that one for housekeeping.
