### ISSUE TITLE
Add New Widget Area in child theme

### ISSUE THREAD

**Issue by yamaks** [understrap/understrap-child#155]
How to correctly add a new widget area in the child theme, saving the widgets of the parent?
My code in the functions.php of the child theme creates widgets in the admin panel, but does not display it on the frontend:

`function skyfly_sidebars_init() {
  register_sidebar( array(
    'name'          => __( 'Телефоны в хедере', 'understrap' ),
    'id'            => 'headerPhones',
    'description'   => '',
    'before_widget'  => '',
    'after_widget'   => '',
    'before_title'   => '',
    'after_title'    => '',
  ) );
}
add_action( 'widgets_init', 'skyfly_sidebars_init' );`

Code in header.php:

`<?php if ( is_active_sidebar( 'headerPhones' )) {
 dynamic_sidebar( 'headerPhones' );}
?>`

![widget](https://user-images.githubusercontent.com/1436067/38926435-543eb282-430b-11e8-8e98-5b99c75f24fd.jpg)

**Comment by Thomas-A-Reinert** [comment]
Hi @yamaks  - you´d also need to add an action to register the sidebar before/after the function in your functions.php like so:

`add_action( 'widgets_init', 'skyfly_sidebars_init' );`

**Comment by yamaks** [comment]
Hi @Thomas-A-Reinert - but in my code there is this action after function:

**Comment by Thomas-A-Reinert** [comment]
Sorry, I overlooked that. Anyhow for some strange reason your solution doesn´t work in fact.
Try the following code, I just tried it and can confirm that it works.

```php
function header_phones_widget() {
    register_sidebar( array(
        'name' => __( 'Телефоны в хедере', 'understrap-child' ),
        'id' => 'header_phones',
        'before_widget' => '',
        'after_widget' => '',
        'before_title' => '',
        'after_title' => '',
    ) );
}
add_action( 'widgets_init', 'header_phones_widget' );
```

Sidenote: You should change the text-domain to understrap-child to keep translation within the childtheme. And I´d recommend using english. If you wanna hardcore that into greek (?) you can also drop the translation function. I know translation for the child-theme text-domain didn´t work until recently. Check my latest pull-request if you need that now.

**Comment by yamaks** [comment]
Excellent! Everything works as it should! Thank you, @Thomas-A-Reinert !

**Comment by Thomas-A-Reinert** [comment]
You´re welcome. Closing this issue for housekeeping..
