### ISSUE TITLE
How to get gulp watch-bs and sass compiling to work for child theme

### ISSUE THREAD

**Issue by blachawk** [understrap/understrap-child#157]
I apologize if this question has been asked before, but I can't seem to find an answer anywhere.  

I have successfully setup gulp watch-bs to work with my parent theme.  But after installing the child theme, and making changes to the child-theme.scss file, there are no changes pushed to the .css version of that file.  How do I watch and compile files from the child theme location?

Do I need to be within my child themes folder from the terminal and do another `npm install` there as well?

Thanks for any help on this

**Comment by Thomas-A-Reinert** [comment]
Hi @blachawk - no problem at all. Please read the documentation of th child-theme, especially section "[Developing With NPM, Gulp, SASS and Browser Sync](https://github.com/understrap/understrap-child#developing-with-npm-gulp-sass-and-browser-sync)" . That should tell you everything.

Short answer: Yes you´ll have to run npm install as well on the child and need to run the gulp tasks from that dir.

I´ll close that issue for housekeeping as this should solve the issue for sure.
