### ISSUE TITLE
Change the order of the enqueue styles

### ISSUE THREAD

**Issue by Norm101** [understrap/understrap-child#159]
Having a problem with the order of the stylesheets loaded.  

Right now the child-theme.min.css loads before several of the plugin stylesheets.  

How can I get it to load last?

**Comment by Thomas-A-Reinert** [comment]
Hey @Norm101 . Probably easiest solution: https://de.wordpress.org/plugins/re-order-css-and-js-loading-order/

But I - personally - am against using a plug for basic functions. So if you want to dig any deeper:
- Copy footer.php from your parent understrap theme. Load css in your footer.php after the `<?php wp_footer(); ?>` code. That will do it for sure. Anyway, it´s still an ugly hack ;)
- More elegant way: https://stackoverflow.com/questions/7896536/ordering-wordpress-stylesheets
You´ll have to find out which priority the css you wanna overwrite has. Start with 99 and raise that number by the hundred if that doesn´t work the first time..

Closing this issue cos I guess it is resolved (95% sure ;) ) - feel free to re-open if the problem remains, okay?
