### ISSUE TITLE
How do I compile theme.scss ?

### ISSUE THREAD

**Issue by solid-pixel** [understrap/understrap-child#162]
Hi, thanks for the enormous amount of effort you put into this, it's amazing!

I'm having an issue, I'm trying to unload **__contact-form7.scss_** because I don't want the theme to style my contact form.
So I've edited **_src/sass/understrap/theme.scss_** and **_sass/child-theme.scss_** , and removed these lines while running `gulp watch `:

`@import "theme/contact-form7";`
`@import "../src/sass/understrap/theme/contact-form7"`

Unfortunately nothing happens in the terminal and the files won't compile, so the styles are still there.

Is there any way I can make gulp to watch those files too, or am I missing something?

Thanks!

**Comment by 0dp** [comment]
I think you have to stop gulp and run it again after the change

**Comment by solid-pixel** [comment]
@0dp  thanks. It seems silly but restarting **gulp watch** did work this time, no idea why as I haven't changed the config file.

Thanks a lot!

**Comment by Thomas-A-Reinert** [comment]
If you want to watch everything like sass, js, php better rund `gulp watch-bs`. This should recompile and reload everything.

Closing this issue as it seems to be fixed. Feel free to re-open.
