### ISSUE TITLE
Using child theme without NPM, Gulp and SASS

### ISSUE THREAD

**Issue by cesarGimenez** [understrap/understrap-child#163]
Hi. I want to know if I can use the child theme without using NPM, Gulp and SASS. Thanks and great wordpress starter theme!

**Comment by Thomas-A-Reinert** [comment]
Yes, you can do that. It´s just not intended to be built like that and your changes will probably cause more bloat than nessessary. But, YES.

**Comment by cesarGimenez** [comment]
Thanks! Im new in theme dev. Is there any tutorial with this workflow or did you know any other boostrap 4 starter theme with only css? Thank you!.
