### ISSUE TITLE
Getting started with Child Theme - new to npm, gulp, browser-sync

### ISSUE THREAD

**Issue by cliffordp** [understrap/understrap-child#164]
I followed this repo's README.md

I'm on Mac and new to npm/gulp/brower-stack.

I initially got an error about permissions on the `wp-content/themes/understrap-child/node_modules` directory. Once I modified the permissions via Finder, I tried `npm install` again and it seemed to work except for an error about jQuery:

```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --scripts-prepend-node-path=auto
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated uws@9.14.0: stop using this version

> node-sass@4.9.0 install /wp-content/themes/understrap-child/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/darwin-x64-57_binding.node
Download complete
Binary saved to /wp-content/themes/understrap-child/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Caching binary to /Users/cmp/.npm/node-sass/4.9.0/darwin-x64-57_binding.node

> node-sass@4.9.0 postinstall /wp-content/themes/understrap-child/node_modules/node-sass
> node scripts/build.js

Binary found at /wp-content/themes/understrap-child/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine

> understrap@0.8.2 postinstall /wp-content/themes/understrap-child/node_modules/understrap
> gulp copy-assets

[23:41:13] Using gulpfile ~/Documents/.../wp-content/themes/understrap-child/node_modules/understrap/gulpfile.js
[23:41:13] Starting 'copy-assets'...
[23:41:13] Finished 'copy-assets' after 148 ms

> understrap-child@0.5.0 postinstall /wp-content/themes/understrap-child
> gulp copy-assets

[23:41:14] Using gulpfile ~/Documents/.../wp-content/themes/understrap-child/gulpfile.js
[23:41:15] Starting 'copy-assets'...
[23:41:15] Finished 'copy-assets' after 28 ms
npm WARN bootstrap@4.0.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

added 138 packages from 142 contributors in 20.527s

Process finished with exit code 0
```

# Questions:

1. deprecated warnings at the top?
1. jquery 1.9.1 - 3 is required, but none is installed:
    1. How is it _not?_ Is `/wp-content/themes/understrap-child/src/js/jquery.js` the wrong location?
    1. Why does it mention both Bootstrap v4.0.0 _and_ v4.1.0?
1. Is `exit code 0` good, bad, or nothing actually happened?

Thanks for the themes and the help!

**Comment by cliffordp** [comment]
And after modifying /wp-content/themes/understrap-child/sass/theme/_child_theme.scss:
```
/usr/local/bin/gulp --no-cache --update child-theme.scss:child-theme.css
[00:06:34] Working directory changed to ~/Documents/.../wp-content/themes/understrap-child
[00:06:35] Using gulpfile ~/Documents//wp-content/themes/understrap-child/gulpfile.js
[00:06:35] Task 'default' is not in your gulpfile
[00:06:35] Please check the documentation for proper gulpfile formatting

Process finished with exit code 1
```

Googling says maybe a `default` should be added to the gulpfile. Might this be correct?

**Comment by Thomas-A-Reinert** [comment]
About 2.1 - Ignore it. WordPress enqueues it´s own jQuery version anyway. I know it´s not clean but we´re currently in the process of optimizing the parent, the child will follow thereafter asap.

Correct, there is no `default` task. There doesn´t have to be one and it´s not intended for us to have one also. See the list of available gulp-commands.

Assigned this issue to @0dp who can tell you more about gulp, kay?

@holger1411 can you explain the reason for 2.2 ?

**Comment by 0dp** [comment]
hi @cliffordp 

> deprecated warnings at the top?
You can ignore those for now. As @Thomas-A-Reinert said, we're working on a fix.

> jquery 1.9.1 - 3 is required, but none is installed: 
As @Thomas-A-Reinert said, WordPress packs its own version, but if you would like to kill the notice run `npm i jquery` from the theme folder. But again it doesn't make a difference.

> Why does it mention both Bootstrap v4.0.0 and v4.1.0?
It's magic man. No it's a general notice made by the bootstrap package, it's referring to the missing dependency in package.json.

> Is exit code 0 good, bad, or nothing actually happened?
Could you please check your npm log file it could be more permission errors`EACCES`

Are you able to run `gulp watch-bs` or other tasks?

**Comment by cliffordp** [comment]
I tried a few things and realized this small project needed to get up-and-running more quickly than continuing troubleshooting... so I searched for alternatives, scrutinized them, and chose https://wordpress.org/themes/wp-bootstrap-starter/

However, I really appreciate your thorough and quick support and think Bootstrap 4 is the bees knees, so I'm glad you're doing cool things with it.

It sounds like you're already trying to make it better/quicker/easier to get started with Understrap so kudos all around. Peace out! (although I may be back someday)

**Comment by BryanMcNair** [comment]
I’ve been struggling with getting my .scss file to update the .css file and actually make style changes.  I’m new to a lot of this so I have uninstalled, re-installed everything from the ground up a few times and it is time to seek some help.
I’m trying to utilize the understrap child theme running all on xampp localhost. The following is what I have set up:
1.	Installed nodejs globally which appears to working properly where I can nmp init into any file directory.  
2.	Inside a folder I named  ‘wwxxx’ I put all my Wordpress files
3.	Created a database and connected with ‘localhost/wwxxx’
4.	Installed ‘Understrap’ theme.
5.	Installed and activated ‘understrap-child’. 
6.	Opened a Bash window in ‘understrap-child’ and verified node and npm was working by checking the version.     node –v    and    npm -v
7.	npm init in the same bash window which I see added the node_modules folder.
8.	$ npm install gulp –save-dev
9.	NOW THIS IS WHERE I see the first problem. When I issue the command 
gulp copy-assets    I get:     $ bash: gulp: command not found
My understanding is that I can add styles to  
wwxxx\wp-content\themes\understrap-child\sass\theme\child_theme.scss   
And it will automatically update one of the 3 child-theme.css files within the css folder.  The following is code for gulpconfig.json and gulpfile.js

wwxxx\wp-content\themes\understrap-child\gulpconfig.js 
{
  "browserSyncOptions" : {
    "proxy": "localhost/wwxxx/",
    "notify": false
  },
  "browserSyncWatchFiles" : [
    "./css/*.min.css",
    "./js/*.min.js",
    "./**/*.php"
  ],
  "paths" : {
    "js": "./js",
    "css": "./css",
    "img": "./img",
		"imgsrc": "./src/img",
    "sass": "./sass",
    "node": "./node_modules/",
    "bower": "./bower_components/",
    "dev": "./src",
    "dist": "./dist",
    "distprod": "./dist-product",
    "vendor": ""
  }
}
wwxxx\wp-content\themes\understrap-child\gulpfile.js 
// Defining requirements
var gulp = require( 'gulp' );
var plumber = require( 'gulp-plumber' );
var sass = require( 'gulp-sass' );
var watch = require( 'gulp-watch' );
var cssnano = require( 'gulp-cssnano' );
var rename = require( 'gulp-rename' );
var concat = require( 'gulp-concat' );
var uglify = require( 'gulp-uglify' );
var merge2 = require( 'merge2' );
var imagemin = require( 'gulp-imagemin' );
var ignore = require( 'gulp-ignore' );
var rimraf = require( 'gulp-rimraf' );
var clone = require( 'gulp-clone' );
var merge = require( 'gulp-merge' );
var sourcemaps = require( 'gulp-sourcemaps' );
var browserSync = require( 'browser-sync' ).create();
var del = require( 'del' );
var cleanCSS = require( 'gulp-clean-css' );
var gulpSequence = require( 'gulp-sequence' );
var replace = require( 'gulp-replace' );
var autoprefixer = require( 'gulp-autoprefixer' );

// Configuration file to keep your code DRY
var cfg = require( './gulpconfig.json' );
var paths = cfg.paths;

// Run:
// gulp sass
// Compiles SCSS files in CSS
gulp.task( 'sass', function() {
    var stream = gulp.src( paths.sass + '/*.scss' )
        .pipe( sourcemaps.init( { loadMaps: true } ) )
        .pipe( plumber( {
            errorHandler: function( err ) {
                console.log( err );
                this.emit( 'end' );
            }
        } ) )
        .pipe( sass( { errLogToConsole: true } ) )
        .pipe( autoprefixer( 'last 2 versions' ) )
        .pipe( sourcemaps.write( './' ) )
        .pipe( gulp.dest( paths.css ) )
        .pipe( rename( 'custom-editor-style.css' ) );
    return stream;
});

// Run:
// gulp watch
// Starts watcher. Watcher runs gulp sass task on changes
gulp.task( 'watch', function() {
    gulp.watch( paths.sass + '/**/*.scss', ['styles'] );
    gulp.watch( [paths.dev + '/js/**/*.js', 'js/**/*.js', '!js/child-theme.js', '!js/child-theme.min.js'], ['scripts'] );

    //Inside the watch task.
    gulp.watch( paths.imgsrc + '/**', ['imagemin-watch'] );
});

// Run:
// gulp imagemin
// Running image optimizing task
gulp.task( 'imagemin', function() {
    gulp.src( paths.imgsrc + '/**' )
    .pipe( imagemin() )
    .pipe( gulp.dest( paths.img ) );
});

/**
 * Ensures the 'imagemin' task is complete before reloading browsers
 * @verbose
 */
gulp.task( 'imagemin-watch', ['imagemin'], function( ) {
  browserSync.reload();

});

// Run:
// gulp cssnano
// Minifies CSS files
gulp.task( 'cssnano', function() {
  return gulp.src( paths.css + '/child-theme.css' )
    .pipe( sourcemaps.init( { loadMaps: true } ) )
    .pipe( plumber( {
            errorHandler: function( err ) {
                console.log( err );
                this.emit( 'end' );
            }
        } ) )
    .pipe( rename( { suffix: '.min' } ) )
    .pipe( cssnano( { discardComments: { removeAll: true } } ) )
    .pipe( sourcemaps.write( './' ) )
    .pipe( gulp.dest( paths.css ) );
});

gulp.task( 'minifycss', function() {
  return gulp.src( paths.css + '/child-theme.css' )
  .pipe( sourcemaps.init( { loadMaps: true } ) )
    .pipe( cleanCSS( { compatibility: '*' } ) )
    .pipe( plumber( {
            errorHandler: function( err ) {
                console.log( err ) ;
                this.emit( 'end' );
            }
        } ) )
    .pipe( rename( { suffix: '.min' } ) )
     .pipe( sourcemaps.write( './' ) )
    .pipe( gulp.dest( paths.css ) );
});

gulp.task( 'cleancss', function() {
  return gulp.src( paths.css + '/*.min.css', { read: false } ) // Much faster
    .pipe( ignore( 'child-theme.css' ) )
    .pipe( rimraf() );
});

gulp.task( 'styles', function( callback ) {
    gulpSequence( 'sass', 'minifycss' )( callback );
} );

// Run:
// gulp browser-sync
// Starts browser-sync task for starting the server.
gulp.task( 'browser-sync', function() {
    browserSync.init( cfg.browserSyncWatchFiles, cfg.browserSyncOptions );
} );

// Run:
// gulp watch-bs
// Starts watcher with browser-sync. Browser-sync reloads page automatically on your browser
gulp.task( 'watch-bs', ['browser-sync', 'watch', 'scripts'], function() { 
} );

// Run: 
// gulp scripts. 
// Uglifies and concat all JS files into one
gulp.task( 'scripts', function() {
    var scripts = [

        // Start - All BS4 stuff
        paths.dev + '/js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        paths.dev + '/js/skip-link-focus-fix.js',

        // Adding currently empty javascript file to add on for your own themes´ customizations
        // Please add any customizations to this .js file only!
        paths.dev + '/js/custom-javascript.js'
    ];
  gulp.src( scripts )
    .pipe( concat( 'child-theme.min.js' ) )
    .pipe( uglify() )
    .pipe( gulp.dest( paths.js ) );

  gulp.src( scripts )
    .pipe( concat( 'child-theme.js' ) )
    .pipe( gulp.dest( paths.js ) );
});

// Deleting any file inside the /src folder
gulp.task('clean-source', function () {
  return del(['src/**/*',]);
});

// Run:
// gulp copy-assets.
// Copy all needed dependency assets files from bower_component assets to themes /js, /scss and /fonts folder. Run this task after bower install or bower update

////////////////// All Bootstrap SASS  Assets /////////////////////////
gulp.task( 'copy-assets', function() {

////////////////// All Bootstrap 4 Assets /////////////////////////
// Copy all JS files
    var stream = gulp.src( paths.node + 'bootstrap/dist/js/**/*.js' )
        .pipe( gulp.dest( paths.dev + '/js/bootstrap4' ) );

// Copy all Bootstrap SCSS files
    gulp.src( paths.node + 'bootstrap/scss/**/*.scss' )
        .pipe( gulp.dest( paths.dev + '/sass/bootstrap4' ) );

////////////////// End Bootstrap 4 Assets /////////////////////////

// Copy all Font Awesome Fonts
    gulp.src( paths.node + 'font-awesome/fonts/**/*.{ttf,woff,woff2,eot,svg}' )
        .pipe( gulp.dest( './fonts' ) );

// Copy all Font Awesome SCSS files
    gulp.src( paths.node + 'font-awesome/scss/*.scss' )
        .pipe( gulp.dest( paths.dev + '/sass/fontawesome' ) );


// _s SCSS files
    gulp.src( paths.node + 'undescores-for-npm/sass/media/*.scss' )
        .pipe( gulp.dest( paths.dev + '/sass/underscores' ) );

// _s JS files into /src/js
    gulp.src( paths.node + 'undescores-for-npm/js/skip-link-focus-fix.js' )
        .pipe( gulp.dest( paths.dev + '/js' ) );

// Copy Popper JS files
    gulp.src( paths.node + 'popper.js/dist/umd/popper.min.js' )
        .pipe( gulp.dest( paths.js + paths.vendor ) );
    gulp.src( paths.node + 'popper.js/dist/umd/popper.js' )
        .pipe( gulp.dest( paths.js + paths.vendor ) );

// UnderStrap SCSS files
    gulp.src( paths.node + 'understrap/sass/**/*.scss' )
        .pipe( gulp.dest( paths.dev + '/sass/understrap' ) );    

    return stream;
});

// Deleting the files distributed by the copy-assets task
gulp.task( 'clean-vendor-assets', function() {
  return del( [paths.dev + '/js/bootstrap4/**', paths.dev + '/sass/bootstrap4/**', './fonts/*wesome*.{ttf,woff,woff2,eot,svg}', paths.dev + '/sass/fontawesome/**', paths.dev + '/sass/underscores/**', paths.dev + '/js/skip-link-focus-fix.js', paths.js + '/**/skip-link-focus-fix.js', paths.js + '/**/popper.min.js', paths.js + '/**/popper.js', ( paths.vendor !== ''?( paths.js + paths.vendor + '/**' ):'' )] );
});

// Run
// gulp dist
// Copies the files to the /dist folder for distribution as simple theme
gulp.task( 'dist', ['clean-dist'], function() {
  return gulp.src( ['**/*', '!' + paths.bower, '!' + paths.bower + '/**', '!' + paths.node, '!' + paths.node + '/**', '!' + paths.dev, '!' + paths.dev + '/**', '!' + paths.dist, '!' + paths.dist + '/**', '!' + paths.distprod, '!' + paths.distprod + '/**', '!' + paths.sass, '!' + paths.sass + '/**', '!readme.txt', '!readme.md', '!package.json', '!package-lock.json', '!gulpfile.js', '!gulpconfig.json', '!CHANGELOG.md', '!.travis.yml', '!jshintignore',  '!codesniffer.ruleset.xml',  '*'], { 'buffer': false } )
  .pipe( replace( '/js/jquery.slim.min.js', '/js' + paths.vendor + '/jquery.slim.min.js', { 'skipBinary': true } ) )
  .pipe( replace( '/js/popper.min.js', '/js' + paths.vendor + '/popper.min.js', { 'skipBinary': true } ) )
  .pipe( replace( '/js/skip-link-focus-fix.js', '/js' + paths.vendor + '/skip-link-focus-fix.js', { 'skipBinary': true } ) )
    .pipe( gulp.dest( paths.dist ) );
});

// Deleting any file inside the /dist folder
gulp.task( 'clean-dist', function() {
  return del( [paths.dist + '/**'] );
});

// Run
// gulp dist-product
// Copies the files to the /dist-prod folder for distribution as theme with all assets
gulp.task( 'dist-product', ['clean-dist-product'], function() {
  return gulp.src( ['**/*', '!' + paths.bower, '!' + paths.bower + '/**', '!' + paths.node, '!' + paths.node + '/**', '!' + paths.dist, '!' + paths.dist +'/**', '!' + paths.distprod, '!' + paths.distprod + '/**', '*'] )
    .pipe( gulp.dest( paths.distprod ) );
} );

// Deleting any file inside the /dist-product folder
gulp.task( 'clean-dist-product', function() {
  return del( [paths.distprod + '/**'] );
} );

**Comment by 0dp** [comment]
You should not run $npm init in the understrap or understrap-child directories. You only do that when **init**ialize a new project.

You do not need to run $npm install gulp –save-dev from the understrap or understrap-child directory. Simply run `npm install` from the understrap directory (or if you are using the child theme, from the understrap-child directory)
This will install all theme dependencies and execute $gulp copy-assets for you.

**Comment by BryanMcNair** [comment]
Ok I went back and: 
1. Deleted the npm and npm-cache from my user/AppData directory.
2. Deleted everything from my wwxxx directory (site folder in htdocs).
3. Deleted my database and created a new one for good measures.
4. Put a set of fresh wordpress files in the wwxxx.
5. Started up WordPress in the browser and up loaded understrap.
6. Up loaded understrap-child theme and activated.
7. Ran `npm install` from the understrap-child directory.

Now I'm getting a 404 which is looking for js/popper.min in the understrap directory.

understrap directory doesn't have a node_modules but my understrap-child does with the js/popper.min

I don't understand when I would need to run $npm. I'm not really running anything as a "project" since its just me working it anyways. So I take it that I don't need to worry with this step at this time.

Thank you so much
Bryan

**Comment by axlright** [comment]
@BryanMcNair Your new workflow looks solid. Regardless of the 404 on `js/popper.min` in the understrap directory, are you able to add / edit styles in the `sass/theme` directory and run `$ gulp styles` and have `css/` files update?

-Alex

**Comment by BryanMcNair** [comment]
No sir. I'm going to spend some time learning more on using gulp on something simple and get back with this later. 
I'm assuming a lot npm commands seen in tutorials aren't necessary when utilizing UnderStrap because they are already included to run automatically with their package.json and gulpfile.js.  Yes, I have a lot to learn.

**Comment by BryanMcNair** [comment]
does sass have to be installed globally on my computer to be able to run node_module gulp-sass?
