### ISSUE TITLE
Any idea why table.table-borderless works in parent theme but not child theme?

### ISSUE THREAD

**Issue by cliffordp** [understrap/understrap-child#165]
The CSS for table.table-borderless is just non-existent in the child theme.
If I switch to the parent theme as active, the styling _does_ exist.

Any idea how/why - or if this is a bug?

Reference: https://getbootstrap.com/docs/4.1/content/tables/#borderless-table

**Comment by holger1411** [comment]
Hi!
Depends on your Bootstrap version used in your parent and child theme.
The child theme comes with its own dependency stack which can be changed independently.

It also means you can have an older BS version in your child theme than in your parent theme.
Check both package.json files and compare the BS version. Make sure both are the same.
If you have to update your child themes package.json run:
`npm upgrade`
followed by:
`gulp styles`

the first command pulls in the new version, the second compiles your CSS from the new BS .scss files.

**Comment by cliffordp** [comment]
ok, thx
