### ISSUE TITLE
License

### ISSUE THREAD

**Issue by noelspringer** [understrap/understrap-child#168]
Hi, can a license please be added to this project?

**Comment by 0dp** [comment]
Hi @noelspringer 

@holger1411 please correct me if I am wrong.
Understrap is under GPL, what you do with this child theme or your own child theme is up to yourself.

**Comment by noelspringer** [comment]
Hi @0dp,

Yes UnderStrap has a GPL license. I guess since the child theme extends UnderStrap that it could be considered to be GPL also.

It's just that I read elsewhere that just because a repo is on GitHub if it doesn't have a license that doesn't mean the code is free to use. It would still be copyright by the owner though.

Having a GPL license in the repo would make it clear what the rights are of the person forking the repo or reusing the code, not that I have any legal training.

**Comment by 0dp** [comment]
I get where you're coming from. Let's wait and see what @holger1411 says

**Comment by noelspringer** [comment]
Thanks @0dp .

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
