### ISSUE TITLE
browsersync issues :  package, local server, theme or pebkac?

### ISSUE THREAD

**Issue by jamiejohnsonkc** [understrap/understrap-child#169]
I'm going to assume it's pebkac...

Hey all. First off, thanks for sharing your theme with the rest of us.  And thanks for your help in advance.  

**tldr;** 
After scrubbing the web for solutions for months, I still can't get browser-sync to work right.  I've read so many things and tried so many fixes that I've lost perspective on how to proceed. So I don't know if I have a question, a bug or just need some direction. 

- windows 10
- node 8.11.2
- gulp 3.9
- gulp-cli 2.01
- browser-sync 2.24.4

**What's not working:** 
- browser sync won't reload after file saves and it won't inject "live" sass/css 
- watch functions do work. file events do trigger tasks, but no changes stream until you manually reload the browser
- no matter the options selected it always reverts to localhost:3000 on opening and then it's a just a blank page that stalls out "waiting for localhost"
- browser-sync UI is accessible via 3001 and external IP address, neither local/external addresses work for the site

**What I've tried**
- updating local server (serverpress), Visual Studio 
- updating, deleting, and reinstalling node, node modules, gulp at (globally and locally)
- confirmed json, gulp syntax 
- reset firewall, antivirus and the god forsaken windows defender security center were reset to defaults and then ensured necessary ports were available and excluded
- ensured all files/folders had necessary permissions
- maximized and reviewed logs for errors and conflicts
- ensured all related CLI/CMD were conducted with admin rights
- reverted back to an unaltered, fresh install of understrap & child, with no modifications to eliminate opportunities for error

**Mixed results**
Since beginning with browsersync I have had some moments of mixed success. Recently I was able to give live sass injection working for a short while. I'm not sure how/why

**So....pebkac?** 
Understrap is my first foray into gulp/browsersync/local WP and sass. I'm sure I've missed something small and obvious somewhere. Problem is I don't know what I don't know at this point. 

Thanks for whatever aid you might pass my way!

Jamie

**Comment by 0dp** [comment]
In the gulp file, under proxy you'll need to set your url.
Then run `gulp watch-bs`

**Comment by jamiejohnsonkc** [comment]
Thanks for helping me out. 

Here's how I have my options set up in gulpconfig.json .  gulp watch-bs yields the results I previously mentioned.  Other than this one alteration, my fork should be an exact match with the master.  

So can I assume the issue is not with understrap? 

{
  "browserSyncOptions" : {
    "proxy": "www.atomic.dev.cc",
    "notify": true,
    "logLevel": "debug",
    "logConnections": true
  },

**Comment by 0dp** [comment]
> no matter the options selected it always reverts to localhost:3000 on opening and then it's a just a blank page that stalls out "waiting for localhost"
This is what cought my attention.

1. Are you working on a local or remote machine?
    1. If local, you've setup a VHOST for the domain www.atomic.dev.cc? so that www.atomic.dev.cc resolves localhost/[name of website folder]

**Comment by jamiejohnsonkc** [comment]
I'm working on a local machine.  .dev.cc is the default domain used by DesktopServer which I use to serve local WP site development and deployment.

I'm not confident I know enough to understand or answer the last part of your question.  So here's some info I thought might be helpful

Here's what happens when I have desktop server & BS running and enter the following into my web browser...

localhost - opens a desktopserver control panel
www.atomic.dev.cc - opens to my site's homepage
localhost/www.atomic.dev.cc 404
localhost:3000
http://192.168.1.206:3000 reverts to BS control panel
localhost:3001 opens BS control panel
192.168.1.206:3001 opens BS control panel 


And here's my debug log of when I run gulp watch-bs from my terminal:



c:\Users\Jamie\Documents\Websites\www.atomic.dev.cc\wp-content\themes\AtomicMouse>gulp watch-bs
[10:51:42] Using gulpfile c:\Users\Jamie\Documents\Websites\www.atomic.dev.cc\wp-content\themes\AtomicMouse\gulpfile.js
[10:51:42] Starting 'browser-sync'...
[BS] [debug] -> Starting Step: Finding an empty port
[10:51:42] Finished 'browser-sync' after 11 ms
[10:51:42] Starting 'watch'...
[10:51:42] Finished 'watch' after 33 ms
[10:51:42] Starting 'scripts'...
[10:51:42] Finished 'scripts' after 25 ms
[10:51:42] Starting 'watch-bs'...
[10:51:42] Finished 'watch-bs' after 18 μs
[BS] [debug] Found a free port: 3000
[BS] [debug] Setting Option: port - 3000
[BS] [debug] +  Step Complete: Finding an empty port
[BS] [debug] -> Starting Step: Getting an extra port for Proxy
[BS] [debug] +  Step Complete: Getting an extra port for Proxy
[BS] [debug] -> Starting Step: Checking online status
[BS] [debug] Resolved www.google.com, setting online: true
[BS] [debug] Setting Option: online - true
[BS] [debug] +  Step Complete: Checking online status
[BS] [debug] -> Starting Step: Resolve user plugins from options
[BS] [debug] +  Step Complete: Resolve user plugins from options
[BS] [debug] -> Starting Step: Set Urls and other options that rely on port/online status
[BS] [debug] Setting multiple Options
[BS] [debug] +  Step Complete: Set Urls and other options that rely on port/online status
[BS] [debug] -> Starting Step: Setting Internal Events
[BS] [debug] +  Step Complete: Setting Internal Events
[BS] [debug] -> Starting Step: Setting file watchers
[BS] [debug] +  Step Complete: Setting file watchers
[BS] [debug] -> Starting Step: Merging middlewares from core + plugins
[BS] [debug] Setting Option: middleware - List []
[BS] [debug] +  Step Complete: Merging middlewares from core + plugins
[BS] [debug] -> Starting Step: Starting the Server
[BS] [debug] Proxy running, proxing: http://www.atomic.dev.cc
[BS] [debug] Running mode: PROXY
[BS] [debug] +  Step Complete: Starting the Server
[BS] [debug] -> Starting Step: Starting the HTTPS Tunnel
[BS] [debug] +  Step Complete: Starting the HTTPS Tunnel
[BS] [debug] -> Starting Step: Starting the web-socket server
[BS] [debug] Setting Option: clientEvents - List [ "scroll", "scroll:element", "input:text", "input:toggles", "form:submit", "form:reset", "click" ]
[BS] [debug] +  Step Complete: Starting the web-socket server
[BS] [debug] -> Starting Step: Starting the UI
[BS] [debug] Setting Option: session - 1529250704654
[BS] [UI] Starting Step: Setting default plugins
[BS] [UI] Step Complete: Setting default plugins
[BS] [UI] Starting Step: Finding a free port
[BS] [UI] Step Complete: Finding a free port
[BS] [UI] Starting Step: Setting options also relevant to UI from BS
[BS] [UI] Step Complete: Setting options also relevant to UI from BS
[BS] [UI] Starting Step: Setting available URLS for UI
[BS] [debug] Getting option via path: urls
[BS] [UI] Step Complete: Setting available URLS for UI
[BS] [UI] Starting Step: Starting the Control Panel Server
[BS] [UI] Using port 3001
[BS] [UI] Step Complete: Starting the Control Panel Server
[BS] [UI] Starting Step: Add element events
[BS] [UI] Step Complete: Add element events
[BS] [UI] Starting Step: Registering default plugins
[BS] [UI] Step Complete: Registering default plugins
[BS] [UI] Starting Step: Add options setting event
[BS] [UI] Step Complete: Add options setting event
[BS] [debug] +  Step Complete: Starting the UI
[BS] [debug] -> Starting Step: Merge UI settings
[BS] [debug] Setting Option: urls - Map { "local": "http://localhost:3000", "external": "http://192.168.1.206:3000", "ui": "http://localhost:3001", "ui-external": "http://192.168.1.206:3001" }
[BS] [debug] +  Step Complete: Merge UI settings
[BS] [debug] -> Starting Step: Init user plugins
[BS] [debug] Setting Option: userPlugins -
[BS] [debug] +  Step Complete: Init user plugins
[Browsersync] Proxying: http://www.atomic.dev.cc
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.206:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.206:3001
 --------------------------------------
[Browsersync] Watching files...


Thanks so much for your help!

**Comment by 0dp** [comment]
and what is the content of your gulpfile.js found in the understrap-child folder

**Comment by jamiejohnsonkc** [comment]
Here you go. 

https://github.com/jamiejohnsonkc/Atomic_Mouse_Theme/blob/master/gulpfile.js

**Comment by 0dp** [comment]
what about `www.atomic.dev.cc:3000` ?

**Comment by jamiejohnsonkc** [comment]
Sorry I meant to include that one earlier. Just spins and spins. Never stops.
