### ISSUE TITLE
Parent theme release version dependency?

### ISSUE THREAD

**Issue by firelite** [understrap/understrap-child#170]
Not sure how to best phrase my question, but is each understrap child theme release strictly dependent on a specific release of its parent theme?  Or otherwise?

For example: 
understrap-child 0.5.2 requires understrap 0.8.2
understrap-child 0.5.1 requires understrap 0.8.1
understrap-child 0.5.0 requires understrap 0.8.0
-or-
understrap-child 0.5.0 requires understrap 0.8.x
understrap-child 0.5.x requires understrap 0.8.x

Thanks!

**Comment by h3imo** [comment]
Would also be interested in this question. Also in how best to upgrade a childtheme. Is there a workflow? Or some things we need to keep in mind?

**Comment by 0dp** [comment]
#101

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
