### ISSUE TITLE
node_modules supposed to be extremely large?

### ISSUE THREAD

**Issue by firelite** [understrap/understrap-child#171]
Hi,

I'd like some help understanding node_modules folder inside understrap-child.  I'm not a regular node.js/npm user and am just getting started with understrap/understrap-child.  Node_modules was populated with hundreds of modules after I performed an update to understrap-child.  

So these are the steps I took: I downloaded a zip of the understrap-child 0.5.2 release, unzipped it, modified some scripts, then I updated it to the 0.5.3 release by replacing the gulpfile.js and package.json files with the 0.5.3 version, ran commands `npm update`, `npm install`, `gulp scripts`, and lastly `gulp styles`.  There were a few other commands I ran to get up to speed, but that's the bulk of it.

From the npm update/install, there's now 756 folders in understrap-child/node_modules amounting to 178.8 MB.  That doesn't feel right.  But please let me know if I'm using it incorrectly.  I feel all those should be installed globally somehow, not all within this theme folder.

Thanks for your help!

**Comment by 0dp** [comment]
Yes, it contains development dependencies.
To compile your final theme to the dist/ folder run `gulp dist`
You will see that folder will not contain development dependencies.

**Comment by holger1411** [comment]
@0dp is right: You just need the dependencies locally to develope your theme. You don´t need to send it to your staging or live server.
Closing this here but feel free to reopen it if there are still questions.
