### ISSUE TITLE
Pagination not working correctly

### ISSUE THREAD

**Issue by nuriye** [understrap/understrap-child#172]
Hi!
I have an Archive Page, there are 48 Posts.
I am showing 24 Posts per Page. Which works.
But shouldn't there be a pagination with the Numbers 1, 2 (since there are 2 Pages 2x24)
But the Pagination is only showing a 1:
![bildschirmfoto 2018-06-20 um 17 59 13](https://user-images.githubusercontent.com/18513929/41723641-dcd0a91a-756b-11e8-9aa3-154857ec84e3.png)

When I disable the Pagination, all 48 Posts are showing.

**Comment by 0dp** [comment]
What version of the parent theme are you using?

**Comment by nuriye** [comment]
Understrap: 0.8.1
Child Theme Understrap: 0.5.0

**Comment by 0dp** [comment]
Could you try and update the parent theme please?

**Comment by nuriye** [comment]
Thank you! I just updated the parent theme and now it is working correctly. Great Work. Thanks @ the understrap team!

**Comment by 0dp** [comment]
@holger1411 please close

**Comment by axlright** [comment]
Closing this issue because it's resolved - thanks @0dp
