### ISSUE TITLE
Initial npm install, scary warnings :)

### ISSUE THREAD

**Issue by jaredsnider** [understrap/understrap-child#173]
Setting up a fresh install on the child theme and getting the following at the end:

added 1198 packages from 728 contributors and audited 25552 packages in 41.316s
found 46 vulnerabilities (6 low, 32 moderate, 8 high)
run `npm audit fix` to fix them, or `npm audit` for details

**Comment by 0dp** [comment]
We're currently working on limiting these warnings.

For your relief I can tell you that none of the packages you install with npm are used in and by theme theme.
They are solely used for when you develop your theme with the gulp tasks, and will not be present in your final distribution.

Therefor you can safely ignore these warnings.

**Comment by jaredsnider** [comment]
Appreciate it!
