### ISSUE TITLE
Hamburger menu doesn't open mobile menu

### ISSUE THREAD

**Issue by Hidieh** [understrap/understrap-child#174]
Hi,

I'm having a problem with opening the menu on mobile. The primary menu works as it should on the desktop, but on mobile, you can see the hamburger icon, but clicking it does not open the menu?

My site: https://www.megasim.eu/talli/

Can't figure this one out. I already once disabled all the plugins and that didn't help. I think I should have all the necessary files (js), haven't removed any. Sadly I currently can't develop this locally and can only work with the online version. So no command line available.

**Comment by 0dp** [comment]
You have an error in your markup
```
<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" data-target="#navbarNavDropdown">
				<span class="navbar-toggler-icon"></span>
			</button>
```

should be

```
<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" data-target="#navbarSupportedContent">
				<span class="navbar-toggler-icon"></span>
			</button>
```

Notice the data-target

You could also change the id of the drop down to `navbarNavDropdown`

**Comment by Hidieh** [comment]
Huge thanks to you, it's nice to get this blind to your own code lol.
