### ISSUE TITLE
Parse error: syntax error when updating to 0.8.2

### ISSUE THREAD

**Issue by tekcap** [understrap/understrap-child#175]
Issue is about..

 a Bug Report
Please tell us about your environment:

WordPress Version: 4.9.7
Updating understrap from 0.7.0 to 0.8.2

No matter the page I visit on my website http://golabo.com/ I get the following error

Parse error: syntax error, unexpected '[' in /home/golaboc/public_html/wp-content/themes/understrap/inc/pagination.php on line 9

I'm not sure what to do, I was given control of the website and I'm not a developer. I was just doing the routine updates and updating content.

**Comment by 0dp** [comment]
What version of php are you using?
