### ISSUE TITLE
where to run npm/gulp commands described in the manual?

### ISSUE THREAD

**Issue by mherda** [understrap/understrap-child#181]
Hi,

As the title suggests, shall I install npm packages and then run gulp in the parent them directory or the child one? The installation notes would suggest that in the parent UnderStrap directory... just wanted to confirm.

Thanks

**Comment by mherda** [comment]
I think I figured it out. All commands (npm install, gulp copy assets and gulp watch) should be run from the understrap-child directory.

Could you confirm that?

If so, could you edit the Readme.md as it says:

> Open your terminal and browse to the location of your UnderStrap copy
> Run: $ npm install then: $ gulp copy-assets
> 

Which, at least I would understand, would mean that I have to run them in the understrap not understrap-child directory.

Thanks for your hard work on this project!

**Comment by 0dp** [comment]
Hi @mherda That is correct!
In the terminal or command prompt navigate to child theme folder and execute commands.
pro tip! npm install will execute gulp copy-assets when it's done. So you just need to execute npm install, when it's done you can get started with hot reload and all the cool features by running `gulp watch-bs`
Remember to configure your local settings in gulpconfig.js first

**Comment by mherda** [comment]
Thanks. Excuse my ignorance - what exactly do I need to change in gulpconfig. Can't I just accept the settings/paths that are specified there?

**Comment by 0dp** [comment]
You will want the proxy url pointing to your site for BrowserSync to work
```
"proxy": "localhost/wordpress/",
```

so if your development site is at, http://localhost/marcins-cool-website/
You'll want to change it to `"proxy": "localhost/marcins-cool-website/",

**Comment by mherda** [comment]
Great. Thank you.
