### ISSUE TITLE
Issue updating minified css file in css folder

### ISSUE THREAD

**Issue by superfein** [understrap/understrap-child#186]
I'm using the basic child theme, v0.5.3 and using the latest version of Understrap parent theme. I have tried many different methods to try to add some lines of CSS to the .navbar-brand class, a default Bootstrap class, but the changes I make do not take effect.

*I'm using Prepros to compile my SASS. 

The changes/additions I add in understrap-child/sass/theme/_child_theme.scss are making it to the bottom of the understrap-child/css/child-theme.css file, but the minified version child-theme.min.css is not being updated at all, so none of the changes are showing up on the frontend.

It's possible there is an issue with the way Prepros is setup? I'm basically using the defaults. 

Any help would be appreciated. As far as I can tell this is either a bug or my compile settings are completely wrong.

**Comment by superfein** [comment]
Apologies, this was an issue with my Prepros settings after all.

**Comment by elias90** [comment]
Hi there, how you resolve this problem?
