### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by ReneKoops** [understrap/understrap-child#189]
Hello,

Its been a while since a worked on a project with Understrap (And Understrap-child-master).
I've updated the theme to the latest version.  
When i try to work on the project and try to edit child-theme-scss i get a lot of errors in my terminal.

```
Error in plugin 'gulp-sass'
Message:
    src/sass/bootstrap4/_variables.scss
Error: argument `$color` of `darken($color, $amount)` must be a color
        on line 170 of src/sass/bootstrap4/_variables.scss, in function `darken`
        from line 170 of src/sass/bootstrap4/_variables.scss
        from line 9 of sass/assets/bootstrap4.scss
        from line 3 of sass/child-theme.scss
>> $link-hover-color:          darken($link-color, 15%) !default;

   ----------------------------^

Details:
    status: 1
    file: /Applications/MAMP/htdocs/nvsa/wp-content/themes/understrap-child-master/src/sass/bootstrap4/_variables.scss
    line: 170
    column: 29
    formatted: Error: argument `$color` of `darken($color, $amount)` must be a color
        on line 170 of src/sass/bootstrap4/_variables.scss, in function `darken`
        from line 170 of src/sass/bootstrap4/_variables.scss
        from line 9 of sass/assets/bootstrap4.scss
        from line 3 of sass/child-theme.scss
>> $link-hover-color:          darken($link-color, 15%) !default;

   ----------------------------^

    messageFormatted: src/sass/bootstrap4/_variables.scss
Error: argument `$color` of `darken($color, $amount)` must be a color
        on line 170 of src/sass/bootstrap4/_variables.scss, in function `darken`
        from line 170 of src/sass/bootstrap4/_variables.scss
        from line 9 of sass/assets/bootstrap4.scss
        from line 3 of sass/child-theme.scss
>> $link-hover-color:          darken($link-color, 15%) !default;

   ----------------------------^

    messageOriginal: argument `$color` of `darken($color, $amount)` must be a color
    relativePath: src/sass/bootstrap4/_variables.scss
```

I think it has something to do with a new update of bootstrap?
Does anyone know i can do about this problem?

Thanks! :)

**Comment by axlright** [comment]
@ReneKoops Which version of the parent undertrap theme and which version of the child understrap_child theme are you using?

**Comment by ReneKoops** [comment]
Hi @axlright!
Thanks for your message.

I see its a really old version: **Versie: 0.1.8**  while the online version is already at 0.5.3

But i've always installed the updates. and in the backend of the site there are no plugin / theme updates available.

What would be the best way to get the latest version of understrap_child on my site?
Download it and replace the files or something?

Thanks :)

**Comment by axlright** [comment]
With an update this large - going from 0.1.8 to 0.5.3 - I'd probably pull the entire 0.5.3 repository / theme, run `npm install` and add back your custom Sass and any other custom child theme files. In addition to pulling the new backbone files like `gulpfile.js`, you're likely going to need to update your `functions.php` and `header.php` as those have changed as well during the many versions between 0.1.8 and 0.5.3.

**Comment by ReneKoops** [comment]
Ho! @axlright 

Thanks for your reply!
I'm going to try this solution.

*fingers crossed.

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
