### ISSUE TITLE
404 error on child-theme.min.js and child-theme.min.css after updating understrap-child

### ISSUE THREAD

**Issue by 2021creative** [understrap/understrap-child#191]
Hi all, firstly a big thank you for all the hard work that has gone and continues to go into this fantastic project!

I have just updated the parent understrap theme to 0.8.7 and in doing so lost some functionality in my child theme. I presumed that this meant I'd have to update the child as well so I've followed the instructions in other issues/tickets and copied gulpfile.js and package.json over and re-run the gulp commands (scripts and styles) but I am getting 404 errors on the child-theme.min.js and child-theme.min.css files!

Not sure if it's related but I'm not convinced that the css map file is updating either.....

I have tried everything I can to track down why this could be happening but to no avail. Has anyone else experienced this or can anyone suggest a possible solution?

Many thanks in advance and keep up the great work everyone!

**Comment by 0dp** [comment]
If you copied the gulp file over, did you also change the references to theme.css, theme.min.css, theme.min.js, theme.js to child-theme.css, child-theme.min.css, child-theme.min.js, child-theme.js ?

**Comment by 2021creative** [comment]
Thanks 0dp, I copied the gulp file from the latest version of the child theme, do I still need to change those refs? I will look into it and hopefully that will sort it out!

**Comment by 2021creative** [comment]
@0dp I have double checked and the gulpfile seems to be creating the correct files. They are there on the server, but the CMS just can't find them and is giving the 404... Strange! Thanks for your assistance thus far

**Comment by 2021creative** [comment]
@0dp Seems like there was a problem because I had two versions of the understrap-child installed. Everything seems better now but I'm back to the original problem which is drop down menus not working!

**Comment by 2021creative** [comment]
For anyone else with this problem, here is what I found:

I had an old understrap-child theme and I was renaming the folder to switch to the new one while testing. As soon a I renamed the old theme (folder and in the style.css), the 404 went away.
