### ISSUE TITLE
Documentation of copy-assets

### ISSUE THREAD

**Issue by leolara** [understrap/understrap-child#196]
It seems gulp copy-assets copies the dependencies installed by npm, but in the documentation comment in https://github.com/understrap/understrap-child/blob/7b7b9ff441de742da7a5ef5c2a90e3af79dd1a23/gulpfile.js#L167 it says it is actually getting them from bower

**Comment by 0dp** [comment]
Thanks, a PR have been created

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
