### ISSUE TITLE
Is it correct the path into /sass/assets/understrap.scss?

### ISSUE THREAD

**Issue by jjpeleato** [understrap/understrap-child#198]
Hi, first of all, Great work with the Understrap project.

According sass/assets files, Exist the one error in the /sass/assets/understrap.scss, the path in the @import is `../../src/understrap/understrap/understrap`, I think that the path has to be  `../../src/sass/understrap/understrap`

Thank you very much. Greetings José J. Peleato Pradel.

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
