### ISSUE TITLE
What file do I edit to change Contact Form 7 syles?

### ISSUE THREAD

**Issue by Castria** [understrap/understrap-child#199]
I'm relatively new to Sass so this may be something obvious that i'm missing but I've tried editing both \understrap-child\src\sass\understrap\theme\_contact-form7.scss and understrap-child\sass\theme\_contact-form7.scss.

Neither of these actually seem to make a difference and I can see in the browser that the CSS isn't getting updated. I'm running gulp watch and this doesn't do anything when I save these files like it does when i edit _child_theme.scss for example so I assume this is where the problem lies.

What am I doing wrong? What needs to be done and which files needs to be edited to change the Contact Form 7 CSS?

**Comment by holger1411** [comment]
Hi!
The watcher task just watches the /sass folder and all of its subfolders and not the /src/sass/ folder.
There you will find source files from 3rd party assets and extensions (like Bootstrap). These files will be overwritten if you pull in updates from theses 3rd party dependencies.
So you should NOT do changes to this files and thats the reason why the watcher did not watch the /src/sass folder...

If you want to use your own version of /theme_contact_form7.scss copy&past it into your /sass folder and import it in your /sass/child-theme.scss file

via:
`@import "contact-form7";`

you can than remove this line from /sass/child-theme.scss:
`@import "../src/sass/understrap/theme/contact-form7";// <-------- Loads some basic styling for contact form 7 plugin`

**Comment by Castria** [comment]
> If you want to use your own version of /theme_contact_form7.scss copy&past it into your /sass folder and import it in your /sass/child-theme.scss file
> 
> via:
> `@import "contact-form7";`
> 
> you can than remove this line from /sass/child-theme.scss:
> `@import "../src/sass/understrap/theme/contact-form7";// <-------- Loads some basic styling for contact form 7 plugin`

That worked perfect. Thanks for the clarification.

I'm new to Understrap but I'm really loving it so just want to say thanks for that too. Great work.

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
