### ISSUE TITLE
Remove "bower install" from README.md

### ISSUE THREAD

**Issue by alesandar** [understrap/understrap-child#20]
Just did another fresh install and noticed that bower.json doesn't exist. I've followed the installation steps. Seems like in 44b6fc905c2d008f66174cb8aeedda95c553a008 you've completely replaced bower with NPM. Correct me if I'm wrong. Otherwise you need to update the installation steps in README.md.

**Comment by Thomas-A-Reinert** [comment]
Merged, no updates for more than 1 1/2 yrs. So i´ll close that for now.
