### ISSUE TITLE
gulp 4.0.0 giving error on post npm install

### ISSUE THREAD

**Issue by itaine** [understrap/understrap-child#200]
$ gulp watch-bs
assert.js:350
    throw err;
    ^
AssertionError [ERR_ASSERTION]: Task function must be specified

Change the following in the gulpconfig.json file and npm install
```
  "devDependencies": {
    "gulp": "3.9.1"
  }
```

**Comment by AleCss81** [comment]
I have the same problem, but i don't have `"devDependencies"` in my gulpconfig.js. Do I have to add it? At what point?

My gulpconfig.js

```
{
  "browserSyncOptions" : {
    "proxy": "localhost/wordpress/",
    "notify": false
  },
  "browserSyncWatchFiles" : [
    "./css/*.min.css",
    "./js/*.min.js",
    "./**/*.php"
  ],
  "paths" : {
    "js": "./js",
    "css": "./css",
    "img": "./img",
		"imgsrc": "./src/img",
    "sass": "./sass",
    "node": "./node_modules/",
    "bower": "./bower_components/",
    "dev": "./src",
    "dist": "./dist",
    "distprod": "./dist-product",
    "vendor": ""
  }
}
```
Thanks

**Comment by 0dp** [comment]
gulp4 is not yet supported

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
