### ISSUE TITLE
Nothing happens after running the command gulp watch

### ISSUE THREAD

**Issue by ahmu83** [understrap/understrap-child#201]
I am modifying the files `/sass/theme/_child_theme.scss & /sass/theme/_child_theme_variables.scss` & then running the commands `npm install & gulp copy-assets` which are successful. After that I am running the command `gulp watch` to build the `.scss` files to the `.css` files but its stuck like this: http://prntscr.com/lii0mv

The problem is it didnt update the files `/css/child-theme.css & /css/child-theme.min.css`

Also I tried to see any logs by appending --verbose to the command `gulp watch --verbose` but nothing was output neither it said it opened the project on a url, nothing.

Any help?

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
