### ISSUE TITLE
Error in header.php.

### ISSUE THREAD

**Issue by benfinn** [understrap/understrap-child#203]
The current header.php, on line 73, says this:

`'walker'          => new WP_Bootstrap_Navwalker(),`

It should say this:

`'walker'          => new Understrap_WP_Bootstrap_Navwalker(),`

Otherwise, it has an error trying to call the wrong class.

**Comment by benfinn** [comment]
Looks like this is a problem with the version of the child theme downloadable from the "Blank Child Theme" link at the [Understrap](https://understrap.com/) site. Downloading a fresh version directly from GitHub resolved the issue.

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
