### ISSUE TITLE
Documentation link for the _child_theme_variables.scss file

### ISSUE THREAD

**Issue by ahmu83** [understrap/understrap-child#206]
Hello, I am opening this issue to ask for a documentation link, other than https://understrap.github.io/ so that I can override the understrap colors using the the scss file /understrap-child/scss/theme/_child_theme_variables.scss

Should I use the bootstrap variables instead? https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss

Thanks!

**Comment by holger1411** [comment]
Hi!

Yes, if you want to overwrite the exitisting Bootstrap variables use the BS variables in _child_theme_variables.scss

If you want to define your own variables use the same file but use other names for it than BS4 already does

**Comment by ahmu83** [comment]
I will try and see if effects are taking place and will update this ticket with the finding +1
