### ISSUE TITLE
Styles in /sass/theme/child_theme.scss not sticking after page reload

### ISSUE THREAD

**Issue by zeronerve** [understrap/understrap-child#207]
Hi, I've modified a few simple styles in /sass/theme/child_theme.scss, and after the gulp sass task runs, the browsersync page shows the changes properly, but if I refresh the page, or load another page, the styles revert.  Any ideas?

the changes I've made include:

 _/sass/theme/child_theme.scss_

body {
    color: #7e838a !important; 
    font-family: demos-next, sans-serif;
    font-weight: 300;
}

.wrapper {
    padding: 0 !important;
}

Is this an issue with the child theme styles not be enqueued properly? It seems like it's only picking up the parent styles.

**Comment by matthieunelmes** [comment]
Having the same problem, only just started happening today

**Comment by andreademasi** [comment]
Same

**Comment by danemorgan** [comment]
The build process has changed several times since this issue was lodged and will change again soon. Additionally, I can confirm that the child theme styles are being built curently.
