### ISSUE TITLE
undrestrap/js/theme.js vs understrap-child/js/child-theme.js

### ISSUE THREAD

**Issue by JOduMonT** [understrap/understrap-child#209]
I wonder why js/child-theme.js exist and why understrap-child just simply don't relay on js/theme.js instead, which is more updated anyway.

**Comment by bacoords** [comment]
By using a separate js file in the child theme, you can add your own custom javascript and still have it bundled into one js file that includes all of the dependencies. You can also potentially modify which files get pulled into the build process. 

I think the other method (including theme.js and creating a separate js file for child theme customizations) would have made sense as well, and both methods basically have trade-offs.
