### ISSUE TITLE
Problem with npm install under my Understrap project

### ISSUE THREAD

**Issue by AleCss81** [understrap/understrap-child#210]
Hi, sorry for my inexperience with npm install.

I'm starting a Wordpress project based on Understrap. I have followed your configuration instruction for developing with Node.js, Gulp and Browser Sync:

**Installing Dependencies**

- Make sure you have installed Node.js, Gulp, and Browser-Sync [1] on your computer globally
- Open your terminal and browse to the location of your UnderStrap copy
- Run: $ npm install then: $ gulp copy-assets

Ok, I have installed globally all components listed on the first step. Then I have reached my Understrap project folder on Windows command prompt.
When then I have run `npm install`, I have received these warning and errors

![image](https://user-images.githubusercontent.com/5421829/51433352-c7fd4c80-1c48-11e9-89e0-85edc7156131.png)

And after run `gulp copy assets` I have received this:

![image](https://user-images.githubusercontent.com/5421829/51433360-f549fa80-1c48-11e9-970e-b61beebb7896.png)

After running `npm install gulp` I have received this

![image](https://user-images.githubusercontent.com/5421829/51433381-4c4fcf80-1c49-11e9-802e-9e0640bd89a4.png)

Finally after try to running again `gulp copy-assets` prompt has said this:

![image](https://user-images.githubusercontent.com/5421829/51433397-8a4cf380-1c49-11e9-9d3c-5bd2474eb78b.png)

I'm not expert with node and npm, but I think there's some problems. What do I have to do to have a correct npm install in my Understrap project and developing with gulp and browser sync?

Thank you very much

**Comment by AleCss81** [comment]
Hi, I have understand my error: I was trying to install npm not inside my understrap project folder.

Now I have launched npm install inside my understrap child theme and this was the result:

![image](https://user-images.githubusercontent.com/5421829/51461744-33d1d900-1d5f-11e9-822a-e69edc8eed59.png)

There are some error and then if I run the gulp copy-assets inside understrap child folder it doesn' work (no such file or directory, scandir 'C:\Users\aless\Google Drive\Staging\test.alecsslab\wp-content\themes\understrap-child\node_modules\node-sass\vendor').

Can you help me? Thanks so much

**Comment by bacoords** [comment]
Hi- This is a known issue. Please pull the latest version of the child theme to address the `npm install` failure
