### ISSUE TITLE
Confusing Bootstrap versions

### ISSUE THREAD

**Issue by twiginteractive** [understrap/understrap-child#213]
I'm new to UnderStrap, so learning the ropes - but I am confused as to the version of Bootstrap included in the latest release of the Child package.

v.0.5.4 is labelled "Bootstrap 4.2.1 update" (which seems to be the Bootstrap version in the latest parent Understrap release)
https://github.com/understrap/understrap-child/releases/tag/0.5.4

However the downloaded source has v4.1.3 in the `/src/sass/bootstrap` directory, and v4.1.0 in the `/sass/bootstrap` directory.

Furthermore, am I reading the dox correctly that the `npm install` (which runs `gulp copy-assets`) should in fact copy the updated libraries from the parent (understrap) folder? Or no?

Thanks for the guidance.

--------------
EDIT: It looks like the v0.5.4 download is actually still v0.5.3, if you believe the version tag in `style.css`. Maybe this release didn't get pushed up correctly?

**Comment by 0dp** [comment]
@holger1411

**Comment by qvarting** [comment]
Yea it would be nice to have bootstrap 4.2.1 in the child theme as well. Have to fix some toasts! 🍞

**Comment by fschoenfeldt** [comment]
I made a pull request updating to latest bootstrap & also changing those variables: https://github.com/understrap/understrap-child/pull/254

**Comment by Thomas-A-Reinert** [comment]
Cannot confirm that everything works smooth with #254 :/ Sorry!

**Comment by bacoords** [comment]
We're now tracking the child theme more closely to the parent theme. Both should be pulling 4.6.0 until we migrate to 5 at some point in the future.
