### ISSUE TITLE
Update Child Theme Bootstrap 4.3.1

### ISSUE THREAD

**Issue by heibie** [understrap/understrap-child#215]
Hi,
I' m using the understrap-child and updated the parent theme to the newest version over the Wordpress Theme Directory (with Bootstrap 4.3.1). As far as i understand, i have to update the child theme also, but i'm not quite sure how to do this. Can you give some support and hints?

Thanks in advance
Heiko

**Comment by 0dp** [comment]
In package.json:28 change to "bootstrap": "4.3.1"
Remove package-lock.json file
Run `npm install`

**Comment by heibie** [comment]
I tried, but get the following error message. Any ideas how to fix this?
Thanks in advance.

```
npm install

> understrap-child@0.5.3 postinstall /xxx/xxx/xxx/xxx/xxx/xxx/wp-content/themes/understrap-child
> gulp copy-assets

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '../lib/completion'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/xxx/xxx/xxx/xxx/xxx/xxx/wp-content/themes/understrap-child/node_modules/.bin/gulp:13:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap-child@0.5.3 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the understrap-child@0.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /xxx/xxx/.npm/_logs/2019-02-19T13_36_23_623Z-debug.log
```

**Comment by 0dp** [comment]
what is the output of `gulp -v`

**Comment by heibie** [comment]
it says:

gulp -v
[15:07:07] CLI version 2.0.1
[15:07:07] Local version 3.9.1

**Comment by 0dp** [comment]
hi @heibie.

My output of gulp -v
```
[20:45:55] CLI version 2.0.1
[20:45:55] Local version 3.9.1
```

I downloaded the theme, changed package.json:28 to `"bootstrap": "4.3.1",`
ran `npm install`

No problem what so ever.

Did you try and remove node_modules before running `npm install`

**Comment by holger1411** [comment]
This file did not updated automatically, because you might have change it (for example comment out some BS assets you don´t need for your process).

If you want to update it by yourself use the original BS4 file as reference here:
https://github.com/twbs/bootstrap/blob/master/scss/bootstrap.scss

If you don´t change it just copy and paste it and adjust the path (via find and replace)

**Comment by heibie** [comment]
ok. i have not changed anything in the file. as far as i can see, all references in this file got to, e.g., "../../src/sass/bootstrap4/functions". so it should use the updated Bootstrap which can be found in the src-Folder.

general question:
is this the best way to update the child theme, if a new Bootstrap-Version is out? Or will the child-theme be updated sometime in general, if a new bootstrap-version is out?

Thanks for your help!

**Comment by holger1411** [comment]
Yes, but BS4.3.1 imports two more files than 4.1.0. 
So it makes sense to update this file.

**Comment by holger1411** [comment]
You can update the file manually, or you can wait till the new understrap-child theme is available here so you could copy&past it here.
Or you can update it manually and than open a pull request here;-)

**Comment by 0dp** [comment]
> Or will the child-theme be updated sometime in general, if a new bootstrap-version is out?
It will be updated, when a PR is created ;)
> Yes, but BS4.3.1 imports two more files than 4.1.0.
Correct, you will need to update `sass/assets/bootstrap4.scss`
with spinners, and toasts

**Comment by holger1411** [comment]
Hey, I updated the file here:
https://github.com/understrap/understrap-child/blob/master/sass/assets/bootstrap4.scss

**Comment by holger1411** [comment]
The child theme isn´t on #1 on my priority list. While I try to release a new parent theme version within days (sometimes hrs) the child theme takes longer.
The main reason is (beside the time factor) that most people using the child theme, customize it heavily (<- that a child theme is made for) and don´t update it from the repo here.
