### ISSUE TITLE
woocommerce gallery images not functioning in understrap-child and draft

### ISSUE THREAD

**Issue by amandablum** [understrap/understrap-child#218]
I've confirmed that this is true in Base and Draft (and I have pulled Base directly from Github for consistency). 
1. Install woocommerce, add product, add feature image and product gallery images to that product. 
2. Go to view that product on front end. The featured image will function correctly, including magnifier.  Thumbnails for featured image and gallery images function fine. (screenshot1)
3. Click on any gallery image except featured image and the image will not appear, you just see white space because the positioning is incorrect. (screenshot2)
4. Can confirm they work fine with understrap or any other theme (Storefront, etc)

Using latest WP, latest Woo, latest Understrap and as I said, this is true in Draft, downloaded last night, and Base, when taken from the site or github. 

![defaultonopeningproductpage](https://user-images.githubusercontent.com/2366499/54882513-1204d900-4e18-11e9-8846-88e1acdb0e00.png)
![clicknoanygalleryimage](https://user-images.githubusercontent.com/2366499/54882518-15986000-4e18-11e9-9ef7-1a8e1bab30f4.png)

**Comment by holger1411** [comment]
Hm, test it here:
https://understrap.com/understrap/?product=a-nice-sign
without problems. With UnderStrap and/or the Base.
Can you post the URL?
Or do you see any errors/warnings in your webdeveloper tools console in your browser?

**Comment by amandablum** [comment]
Understrap works fine, its the child themes. 

There are no errors in the console except for `[Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details. (anonymous) @ content.script.js:1`

url is https://ceremonyclay.com/product/artichoke-vessels/

**Comment by holger1411** [comment]
hmm, strange thing. If I load the compiled css file from the parent theme on your site it works, if I use the compiled stuff from the child it did not work...so its definitely a child theme css problem...

**Comment by amandablum** [comment]
right. but I haven't altered the child theme css or js. Its out of the box.

**Comment by holger1411** [comment]
Okay, we used some woocommerce.scss stuff in the parent theme for it. This was also pulled into the child theme via npm ....but it was never added via @import to the main .scss file. So it was never compiled into the CSS file...
I fixed it here:
https://github.com/understrap/understrap-child/blob/master/sass/child-theme.scss#L4
If I rebuild the css than and test it on your website ... it works.
Feel free to download this new version of the UnderStrap base child theme, add you changes and than rebuild it.

**Comment by holger1411** [comment]
Oh, and thx @amandablum for finding this bug!

**Comment by amandablum** [comment]
thank you for taking seriously my bug report:)  while I have your attention:  this is also true in Draft, which is not on github from what I can see, so please fix there, and on the understrap site, please fix the header file on line 73 in draft, its still pulling the wrong walker nav. but I defend it is a very good way of filtering out ppl who can't fix an easy prob from bugging you for support ;)

**Comment by arumcomputer** [comment]
I am having the same issue using the newest child theme. But I cannot fix it, because the mentioned fix was already applied in master.
Do you have any idea on fixing this issue?

**Comment by danemorgan** [comment]
This issue was resolved in March 2019.

**Comment by travcannon** [comment]
Hi @danemorgan Wondering if the fix was integrated with newer versions of understrap. I am having this same issue. http://3.234.241.24/product/focus/

**Comment by bacoords** [comment]
This was updated in later versions of Understrap, though it depends on what version child theme you used (you can see this in the package.json file). There are some unrelated JS errors when I view the site, which may be causing issues as well
