### ISSUE TITLE
overview excerpt lenght

### ISSUE THREAD

**Issue by BMorenoLg** [understrap/understrap-child#220]
I'm trying to overwrite the excerpt number with the following code:
```

remove_filter( 'excerpt_length', 'wp_trim_excerpt', 999 );
add_filter( 'excerpt_length', 'understrap_custom_excerpt_length', 999 );


function understrap_custom_excerpt_length( $length ) {
        if ( is_admin() ) {
                return $length;
        }
        return 20;
}
```

but I have not managed to change the excerpt.

Is there something wrong?

**Comment by fredperes** [comment]
I'm having the same issue.

**Comment by Thomas-A-Reinert** [comment]
Afaik this is a general WordPress issue and not an UnderStrap/UnderStrap Child problem. 

So that´s why I´ll close this issue. Sorry guys. In case you can confirm that this is an UnderStrap-Only problem I´d be glad to hear back from you and look into a fix.
