### ISSUE TITLE
Gulp minifycss task broken due to extra }

### ISSUE THREAD

**Issue by TC72** [understrap/understrap-child#223]
In gulpfile.js line 90 in the minifycss task there is an extra } which means the minified version is never built:
`  return gulp.src( `${paths.css}/child-theme.css}`, { allowEmpty: true } )`

It makes it look for child-theme.css} as the cource file which doesn't exist and then breaks silently because allowEmpty is set to true.

This took me hours to find so hope this can be fixed before it affects anyone else. I'm going to try to push the fix but it's my 1st time trying ;-)

I've added the fix and created a pull request:
#224

**Comment by bacoords** [comment]
This has been merged.
