### ISSUE TITLE
custom-javascript.js not compiling using child gulpfile.js

### ISSUE THREAD

**Issue by andrewtrecha** [understrap/understrap-child#225]
I spent a good deal of time following all the posts in regards to how to get custom javascript to compile in child-theme.js and child-theme.min.js to no avail. 

I moved my custom-javascript.js file into /src/js/custom-javascript.js, and everything else I followed indicated that it should work. According to the latest build, it looks like all I needed to do was add a custom-javascripts.js file - which is not included in the build, though it is referenced in the gulpfile.js - run gulp watch, add some code, save and I should see the code in child-theme.js. 

What I ended up doing that worked for me is I copied the gulpfile.js from the parent Understrap theme, changed any reference to 'theme' to 'child-theme' and, lo and behold, it finally worked. 

I'm not sure if there is anything in the child theme gulpfile.js file that was specific to the child theme, and in reviewing the files side by side, they are very few differences.

Given the issues and what ended up working, is it likely that understrap-child's gulpfile should be updated?

**Comment by ramojej** [comment]
I'm also having this problem too. Though in my previous works, I didn't encounter this.  Codes in my custom.js file are being compiled to child-theme.js, but not being minified to child-theme.min.js..

**Comment by JulieRegan** [comment]
I was having the same issue.

There was a missing / before js/ and an extra , after custom-javascript.js` in gulp scripts.

It worked as follows: 

`${paths.dev}/js/custom-javascript.js`

**Comment by ramojej** [comment]
> I was having the same issue.
> 
> There was a missing / before js/ and an extra , after custom-javascript.js` in gulp scripts.
> 
> It worked as follows:
> 
> `${paths.dev}/js/custom-javascript.js`
You mean like this?

![image](https://user-images.githubusercontent.com/12524474/56895899-e8953800-6abc-11e9-99e8-70d9069000bd.png)

**Comment by ramojej** [comment]
@andrewtrecha can I see your custom-javascripts.js file?

**Comment by andrewtrecha** [comment]
Thank you @JulieRegan! I should have know it was something is trivial as that.
Did a new clean install WordPress and understrap child, updated gulpfile.js, created custom-javascript.js, ran gulp watch, added js to custom-javascript.js and it compiled as expected. I'm hoping someone will get around to updating that so others don't run into the same problem. Consider this closed.

**Comment by axxelben** [comment]
> I was having the same issue.
> 
> There was a missing / before js/ and an extra , after custom-javascript.js` in gulp scripts.
> 
> It worked as follows:
> 
> `${paths.dev}/js/custom-javascript.js`

Thank you so much  !
