### ISSUE TITLE
editing css in theme editor wordpress not working

### ISSUE THREAD

**Issue by dbaettig** [understrap/understrap-child#228]
Is there no way of editing the style.css file inside wordpress in the theme editor? 
If its just minor changes i would rather do them in the theme editor than having to upload my site to the server over again.
I understrand I cant change the scss file since it wont be compiled but changing 
in the style.css file directly should work right? 

See attachment:
![Skärmavbild 2019-05-10 kl  09 21 41](https://user-images.githubusercontent.com/32362364/57509659-1cfec480-7305-11e9-805a-bb6d34c3264c.png)

**Comment by xicubed** [comment]
I doubt that would work, from the README...

- The theme itself uses the `/style.css`file only to identify the theme inside of WordPress. The file is not loaded by the theme and does not include any styles.

You can see in the functions.php it only encodes the one stylesheet from the result of the sass compile.

**Comment by Thomas-A-Reinert** [comment]
In my opinion - and I guess I am not alone with it according to security settings - editing plugin as well as theme editing should be disabled in any case, anyway. In case you want that - well, find your ways around but we (i dare to speak for whole team understrap in that case!) will not really support that. For a reason.

The still not recommended way for you would be to go to design - css and add anything you want to add up there. This should work.

**Comment by Thomas-A-Reinert** [comment]
Sidenote: As my solution should fulfill your requirements, i´m closing your issue. In case you got any follow-ups just comment or re-open, okay?
