### ISSUE TITLE
adding jQuery custom file

### ISSUE THREAD

**Issue by redknite** [understrap/understrap-child#234]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [x] a Question
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2.x
  - **OS Version:** [Windows 7 | ]
  - **Browser:** [| Chrome XX | Firefox XX  ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

I'm still new to the idea of node and compiling files so please bear with me.  I added a js file "custom-javascript.js" to my /js directory and compiled using gulp watch-bs.  There doesn't seem to be a change in my site though.

When I look in my browser console under child-theme-min.js I only see this note (starting with):
```!function(t,e){"object"==typeof exports&&"undefined"!```

but that's on the demo too so I don't think it's a problem.

I'm wondering if its in the formatting my my actual js file though.  (again I'm new at JS)

I had a differnt site that was using webpack and the js file was like this:

```
import $ from 'jquery';

class Search {
  // 1. Describe and create/initiate our object
  constructor() {
    this.addSearchHTML();
    this.openButton = $(".js-search-trigger");
    this.closeButton = $(".search-overlay__close");
    this.searchOverlay = $(".search-overlay");
    this.searchField =  $("#search-term");
    this.resultsDiv = $("#search-overlay__results");
    this.events();
    this.isOverlayOpen = false;
    this.isSpinnerVisible = false;
    this.previousValue;
    this.typingTimer;
  }

...

export default Search;

```
which was then compiled differently.  

I also tried starting the file like this:

```(function($) {```

or 

```jQuery(document).ready(function($) {```

but I'm not sure what the actual problem is.

UPDATE:
i changed my custom-javascript.js to just

```alert("hello");```

and recompiled.  No alert.  I also tried moving the file to src/js/ and it didn't work there.

**Comment by Thomas-A-Reinert** [comment]
I´m not going to dig into your js-code, but you should write your custom-javascript.js in `./src/js/custom-javascript.js` NOT in `./js/custom-javascript.js` ;)
That should do the job.

**Comment by redknite** [comment]
Thomas.  Thanks for the reply.  That's what I'm saying is that it's not working.

I have a file custom-javascript.js and i've placed in the src/js and also tried in /js  (with running the gulp watch-bs the entire time and even trying to reload the browser manually and I not getting the alert.

contents of custom-javascript.js was: 

```alert ("hello");```

and after your post i also tried repeating the whole process with:

```window.alert ("Test");```

yet still am receiving no alert.

**Comment by redknite** [comment]
UPDATE... figured it out.

in gulpfile.js on line 134 it reads:
        `${paths.dev}/js/custom-javascript.js`,

the problem is its missing a slash "/".  It should read:

        `${paths.dev}/js/custom-javascript.js`,

I changed that and the alert showed up.

**Comment by Thomas-A-Reinert** [comment]
Thanks, for the update!
Yes, you´re absolutely right. I just pushed a fix for this and also added an empty custom-javascript.js to ./src/js/
