### ISSUE TITLE
Dropdown Menu not working Syntax Error

### ISSUE THREAD

**Issue by ghost** [understrap/understrap-child#235]
Hi there,
using the latest understrap-child and my dropdown menu is not working

`SyntaxError: '?#' is not a valid selector child-theme.min.js:1`

I have already copied the Child-theme.js and child-theme.min.js from Github but no luck.

What can I do?

**Comment by danemorgan** [comment]
The current `main` dropdown menu is working for both parent and child themes. Please download the newest code.
