### ISSUE TITLE
Can't override sidebar 

### ISSUE THREAD

**Issue by Utter** [understrap/understrap-child#236]
[SOLVED]

I've had great success (and fun) with understrap+child so far but I've been unable to override the settings and templates for sidebars in the same manner I have with pages, archive and single templates.

In sidebar-right.php it appears you can set the default column width of a sidebar depending on whether one or both are enabled. I want to be able to restrict sidebar right to 3 columns as default but copying sidebar-right.php to the root of the child directory and amending it has no effect. I see that the call to 'get_template_part( 'global-templates/sidebar', 'right' ') comes from within right-sidebar-check.php but I have no idea how to override this. Copying both files to /child has no effect.

Do I need to write a function or unset something to get this to work?

Thanking you in advance for any help.

Keith

**Comment by bacoords** [comment]
I'll close this because it's marked as solved, but if anyone else has this problem - please open a new issue.
