### ISSUE TITLE
What is your routine / practice when developing using understrap-child?

### ISSUE THREAD

**Issue by ramojej** [understrap/understrap-child#238]
I mean how do you guys design the backend (CMS) of your porjects? I just want to know if I'm doing it right.

My process is, my contents are all in ACF. Do you use builders for the contents? And if yes, what builder? Cause I hard code mine. 

How about optimizing your sites (Google Page speed insights)?

Thanks, guys. I've built at least 4 sites using Understrap and I just want to make sure if I'm doing it the correct way.

**Comment by ramojej** [comment]
Anyone using this https://www.dopewp.com/why-livecanvas/ ?

**Comment by Thomas-A-Reinert** [comment]
Abuse reported.
