### ISSUE TITLE
Why are you including the "src" and "css" folders in this repo?

### ISSUE THREAD

**Issue by jacob87o2** [understrap/understrap-child#239]
Since the external dependencies are pulled using npm, and the css are generated, the repo could be downsized by not including those files. 

Is there any reason not to do that? Not trusting in npm modules safety?

If not removing those files, maybe at least a hint in the README, that those files can be ignored?

**Comment by jacob87o2** [comment]
Way to go, closing all the issues without any explanation 😡

**Comment by danemorgan** [comment]
This issue has had no interest or activity in 1 year, 11 months and 10 days.

**Comment by 0dp** [comment]
@jacob87o2 there is an active discussion on the parent theme, on this exact topic going on. So feel free to participate and come with good ideas and knowledge.
Thanks for raising the issue in the first place.

The issue should be closed though, because it needs to be implemented in the parent first and then trickle to the child.

**Comment by jacob87o2** [comment]
@danemorgan It's still not a reason to close it without any word of explanation.

@0dp Thanks for the answer, now it's ok to close it. Could you just post a link to that discussion here (because I couldn't find it)?

**Comment by 0dp** [comment]
hey @jacob87o2 
I'll just leave a link to the discussion area here: https://github.com/understrap/understrap/discussions/

There are bits an pieces everywhere like here, https://github.com/understrap/understrap/discussions/1358

**Comment by ironicmoka** [comment]
> @danemorgan It's still not a reason to close it without any word of explanation.
> 
> @0dp Thanks for the answer, now it's ok to close it.
> Could you just post a link to that discussion here (because I couldn't find it)?

Hi @jacob87o2!
My two cents: including the src files grant users with low coding skills or dev habits to get right on board and start playing around from the get go. I myself the first times I worked with understrap-child ignored all npm and gulp stuff for a while just compiling scss with other tools and messing around with the usual WordPress theme hierarchy in php. I know the repo could be cleaner and tidy up a bit but that would create (imho) a bit of resistance for adoptions in the user base not yet skilled in local development.

**Comment by 0dp** [comment]
Hi @ironicmoka 
Would you mind adding that to the discussion on the parent theme ie. In the bs5 thread where i just proposed tjat we move everything into src 🙈

**Comment by danemorgan** [comment]
> @danemorgan It's still not a reason to close it without any word of explanation.

Explanations have been added to each issue that I closed.

**Comment by danemorgan** [comment]
> Hi @ironicmoka
> Would you mind adding that to the discussion on the parent theme ie. In the bs5 thread where i just proposed tjat we move everything into src

For the record, that conversation can be found [here](https://github.com/understrap/understrap/discussions/1275#discussioncomment-1133747)

**Comment by jacob87o2** [comment]
> Explanations have been added to each issue that I closed.

Nice, thanks!
