### ISSUE TITLE
Source Maps Not Working

### ISSUE THREAD

**Issue by coisty1856** [understrap/understrap-child#24]
For some reason my source maps aren't working in either Chrome or Edge. The source map file is being created and it's referenced in the child-theme.min.css file, but I can't see it in the developer toolbox. The inspector is only showing the child-theme.min.css file

**Comment by rzariy** [comment]
I think that's because it create map from child-theme.min.css not from source file (scss).
adding sourcemap in sass task, worked for me, it create map from scss file.

`gulp.task('sass', function () {
    var stream = gulp.src('./sass/*.scss')
        .pipe(plumber())
	.pipe(sourcemaps.init()) // add this
        .pipe(sass())
	.pipe(sourcemaps.write('./')) // add this
        .pipe(gulp.dest('./css'))
        .pipe(rename('custom-editor-style.css'))
        .pipe(gulp.dest('./css'));
    return stream;
});`

Ps;
I dont't know it's a right way or not since I'm new in gulp.

**Comment by SergiArias** [comment]
I think it should be implemented in next version. Super elegant and effective.

**Comment by coder618** [comment]
@ezrx Thanks man, Your method is working, do you have any idea why this line 
`.pipe(rename('custom-editor-style.css'))`
is necessery

**Comment by ezrx** [comment]
Hi @coder618 I'm glad it's working,
to creating sourcemap is init sourcemap from scss > compiling scss > write map and add compiled destination, so  I think that's line is unnecessery, thats line is from its original workflow and I don't think to touch it,
It's renaming child-theme.css to custom-editor-style.css and I don't have idea what thats css file use for.

**Comment by Thomas-A-Reinert** [comment]
Should be fixed by now. Closing this issue for housekeeping.
