### ISSUE TITLE
How to write path .json

### ISSUE THREAD

**Issue by 7happy** [understrap/understrap-child#240]
I just started programming.
I am using Visual Studio Code with Live Sass Compiler and found that I need to change the path because it makes css files on the same folder.
I think I should write something on settings.json.

{
"liveSassCompile.settings.formats":[
{
"format": "expanded",
"extensionName": ".css",
"savePath": "../../css"
}
]
}

Doesn't work at all.

Can you tell me how should I write the path?
Thank you.

UnderStrap Child Version:      0.5.5
Visual Studio Code 
Live Sass Compiler

**Comment by ironicmoka** [comment]
Have you tried with `"savePath": "~/../css/"` ?
