### ISSUE TITLE
Understrap child doesn´t show any font awesome icons

### ISSUE THREAD

**Issue by melaniemuellerdesign** [understrap/understrap-child#248]
After updating understrap child, font awesome isn´t shown anymore.

e.g.

`/* Font Awesome uses the Unicode Private Use Area (PUA) to ensure screen
   readers do not read off random characters that represent icons */
.fa-glass:before {
  content: ""; }`

**Comment by lukababu** [comment]
I can see font awesome files are in the source but my icons don't seem to be loading either.

Was wondering if you figured it out?

**Comment by danemorgan** [comment]
Font awesome is working in the current code. Please download the newest `main` branch code for both parent and child themes.
