### ISSUE TITLE
Change node version of running project 

### ISSUE THREAD

**Issue by Meet008** [understrap/understrap-child#249]
So, basically i am doing my project in node version 11 with gulp version 3.9.0 and it's perfectly running but now all i want is to move node version 12 so that what changes i should do to run my project.. I already installed gulp version 4 but it's not working so please elaborate the solution..

**Comment by 0dp** [comment]
Did you update gulp-cli?

What is the output of `gulp -v`

**Comment by Meet008** [comment]
CLI version-2.2.0
Local version-4.0.2

**Comment by Meet008** [comment]
### ### WHEN I DO NPM START> 

 server-starter-kit@1.0.0 start /home/meet/workspace-drivelt/Backend
> gulp serve

[12:21:16] Requiring external module babel-register
Mon, 20 Jan 2020 06:51:17 GMT uncaughtException: Task function must be specified
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/meet/workspace-drivelt/Backend/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/meet/workspace-drivelt/Backend/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/meet/workspace-drivelt/Backend/gulpfile.babel.js:53:6)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at loader (/home/meet/workspace-drivelt/Backend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/home/meet/workspace-drivelt/Backend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server-starter-kit@1.0.0 start: `gulp serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server-starter-kit@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/meet/.npm/_logs/2020-01-20T06_51_17_263Z-debug.log

**Comment by 0dp** [comment]
In the readme file the correct commands are listed

**Comment by Meet008** [comment]
what's the need of that??

ok leave it..i got the error..actually i need to define different tasks in series because i am using gulp version 4 so please suggest how to define multiple tasks in series in gulpfile.js

**Comment by 0dp** [comment]
What the need for using the correct commands are?

The child theme is hopelessly behind the main theme.
If you want to fiddle around with the gulp tasks, I propose you take a look at the parent themes tasks.

@UnderstrapFramework

**Comment by UnderstrapFramework** [comment]
@0dp thanks for tagging me

I'm very inexperienced with NPM/Gulp if i'm honest so i'm gonna be of no help

**Comment by 0dp** [comment]
It was more so you know that childtheme needs priority to be up to speed with the parent

**Comment by UnderstrapFramework** [comment]
@0dp good point

**Comment by Meet008** [comment]
### Readme.md file:-


# Server-Starter-Kit
> Kick start developing business logic without worry about base project structure with
  testing, code coverage support, eslint config etc.

### Prerequisites
Before start development. Please install.

```
node: >=4.8.0
```
```
npm : >=2.15.11,
```
```
yarn: >=0.20.3
```

### How to do git commit?
First of all add your changes into staging by using
```shell
git add <changedFile.ext>
```

and then 
```shell
yarn commit
```

this would ask few questions like type, scope, short description, detail explanation,
closing issues  of the changes.

![commit window](https://cdn-images-1.medium.com/max/800/1*tB1XTkxryDmMXGcls-qe5Q.png)

### Files to be created when cloned
#### to create .env file
```shell
cp .env.example .env
```


#### to create log files
```shell
somefile.log
exceptions.log
```
```shell
config/somefile.log
```
File to be created in config directory




### Gulpfile:-

/*eslint-disable*/
import gulp from 'gulp';
import gulpLoadPlugins from 'gulp-load-plugins';
import path from 'path';
import del from 'del';
import runSequence from 'run-sequence';
import apidoc from 'gulp-apidocjs';

const plugins = gulpLoadPlugins();

const paths = {
  js: ['./**/*.js', '!dist/**', '!node_modules/**', '!coverage/**'],
  nonJs: ['./package.json', './.gitignore', './.env', './**/*.log'],
  tests: './server/tests/*.js',
};

// Clean up dist and coverage directory
gulp.task('clean', () =>
  del.sync(['dist/**', 'dist/.*', 'coverage/**', 'docs/**', 'docs/.*', '!dist', '!coverage', '!docs'])
);

// Create api docs.
gulp.task('apidoc', (cb) => {
  apidoc.exec({
    src: 'modules/',
    dest: 'docs/',
  }, cb);
});

// Copy non-js files to dist
gulp.task('copy', () =>
  gulp.src(paths.nonJs)
    .pipe(plugins.newer('dist'))
    .pipe(gulp.dest('dist'))
);

// Compile ES6 to ES5 and copy to dist
gulp.task('babel', () =>
  gulp.src([...paths.js, '!gulpfile.babel.js'], { base: '.' })
    .pipe(plugins.newer('dist'))
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.babel())
    .pipe(plugins.sourcemaps.write('.', {
      includeContent: false,
      sourceRoot(file) {
        return path.relative(file.path, __dirname);
      },
    }))
    .pipe(gulp.dest('dist'))
);

// Start server with restart on file changes
gulp.task('nodemon', ['apidoc', 'copy', 'babel'], () =>
  plugins.nodemon({
    script: path.join('dist', 'index.js'),
    ext: 'js',
    ignore: ['node_modules/**/*.js', 'dist/**/*.js', 'docs/.*', 'docs/**/.*'],
    tasks: ['copy', 'babel'],
  })
);

// gulp serve for development
gulp.task('serve', ['clean'], () => runSequence('nodemon'));

// default task: clean dist, compile js files and copy non-js files.
gulp.task('default', ['clean'], () => {
  runSequence(
    ['apidoc', 'copy', 'babel']
  );
});

**Comment by Meet008** [comment]
Actually i am intern right now. I don't have much idea what should i do. So, can u please tell me what should i actually do??

**Comment by 0dp** [comment]
@Meet008 are you even in the right place?
This is a WordPress child theme repo.

What is all this server-starter-kit thing?

**Comment by 0dp** [comment]
Woopsy Daisy 😉
