### ISSUE TITLE
Hamburg doesn't show up on mobile

### ISSUE THREAD

**Issue by idpokute** [understrap/understrap-child#25]
Hi,
Hamburg doesn't show up on mobile.
I resized the browser window on Chrome, and it didnt' show up.

Thanks.

**Comment by holger1411** [comment]
Hi!

Which UnderStrap version do you use?
Do you replace the original header.php from the parent in your child?

**Comment by idpokute** [comment]
Hi @holger1411 
Understrap version is 0.5.0, and Child theme version is 0.1.5 Both are the latest versions.
I didn't replace the original header.php, cause I wanted to use parent's header.php

**Comment by holger1411** [comment]
Hm, do you habe an URL for us?

**Comment by idpokute** [comment]
here is the url; http://www.senna-design.com/

**Comment by holger1411** [comment]
Hi!
Thx for the URL.
Pls run:
`npm update`
followed by
`gulp copy-assets`
in your browser.
Than recompile it by
`gulp sass`

**Comment by holger1411** [comment]
Explanation: The parents header.php use a new markup to refelct the changes from Bootstrap 4 Alpha 4 to Alpha 5.
If you use the child before and don´t update and recompile the assets you use the new css styles for the old markup...

**Comment by idpokute** [comment]
@holger1411 do you mean I need to run the command in child theme directory? or need to run the commend parent theme also?

**Comment by holger1411** [comment]
No, just in the child theme directory.
The parent theme css files are obsolet, because the child use this files from the node package to compile the final output.

**Comment by idpokute** [comment]
@holger1411  I run the commend then it bring some issues.
Here is the screenshot.
![bs4](https://cloud.githubusercontent.com/assets/5393574/20223225/9572a96c-a806-11e6-9237-83ed211985ca.png)

1.hamburger doesn't appear beside site name, but I can click it.
2.When you click the hamburger, menu appears on the left hand side first. Then it moves to the right hand side.
3.When I click a menu item that has sub-menu, sub-menu appear. However, its behavior is same as desktop's. Thus the sub-menu shows on the right hand side.

I hope this issues improve child-theme.
Thanks.

**Comment by Thomas-A-Reinert** [comment]
Issue is more than 1 1/2 yrs old now with now further follow ups. Closing it for housekeeping. Feel free to reopen if needed.
