### ISSUE TITLE
How to improve the child-theme performance

### ISSUE THREAD

**Issue by EllieMaffio93** [understrap/understrap-child#250]
Good morning,
I have a problem with a website created with the Understrap theme and developed on the Child.
The problem is related with the speed of the website when loaded in its mobile version: performances are really bad.
When checking out the website on "PageSpeed Insights", it appears that the problem is linked with the great dimensions of the css files and javascripts. I already minify the css and js (custom) files using NPM and Gulp.

So, my question is: is there a further way to minify these files, in order to get better performances from the theme? Or any other way to make my website load faster in its mobile version?
Here's the link to the website: https://paveandgo.de/

Thanks for your help!

**Comment by axlright** [comment]
@EllieMaffio93 compiled Bootstrap CSS itself is pretty large. One way you can reduce the file size of the compiled CSS is to go into `sass/theme/assets/bootstrap4.scss` and comment out any modules of Bootstrap that you're not using. Doing this can make a big difference.

I use an UnCSS gulp function to remove all unused CSS but it's kinda a pain.

Most of my UnderStrap child theme sites get 96+ in Google Lighthouse performance, so it's definitely possible.

**Comment by valeliasvi** [comment]
hello @axlright 
Thank you for your tip on improving the child theme performance, that helped.

I am having another related issue, not sure if you can help with that too. 
I am trying to edit the `src/fontawesome/_path.scss` file to include `font-display: swap;` but it is not updating the `child-theme.css` final file. I am not familiar with gulp, I tried to `gulp copy-assets again` but it didn't help. Am I doing something wrong?

I would appreciate it a lot if you could help! Thanks!

**Comment by axlright** [comment]
@valeliasvi You have two options -

1) you can copy the `src/fontawesome/_path.scss` file to your `sass/theme/` directory, edit it and then change `sass/assets/font-awesome.scss` to call your edited version with `@import "../theme/path";` instead of `@import "../../src/sass/fontawesome/path";`
or
2) you can add a line of custom Sass into any of your custom theme Sass files, and this will be compiled in addition to the stock Font Awesome style

```
@font-face {
  font-family: 'FontAwesome';
  font-display: swap;
}
```
Haven't tested the #2 approach but I'd think it'd work. Good luck!

**Comment by valeliasvi** [comment]
The first option worked beautiful!
Thank you!!!!!

**Comment by EllieMaffio93** [comment]
Thanks  @axlright for your answer. That could really help me!
Since I already use Gulp, I'm wondering if you could please share with me the gulp function you were talking about in your message. Why is it kinda a pain to use? Do you think it would be better and faster to clean up the bootstrap CSS file by commenting out any modules I don't use?

Thank you again for your help!

**Comment by Thomas-A-Reinert** [comment]
Just a sidenote: DO NOT EDIT FILES FROM ./SRC !!! All those changed will get lost with an npm update.

And yes, just comment out any includes you won´t use at all. That´s already half-way down the road. ALL my sites load within less than a second with caching (W3TC) enabled that way.
