### ISSUE TITLE
gulp copy-assets fails

### ISSUE THREAD

**Issue by seanhudson** [understrap/understrap-child#251]
Having an unusually difficult time getting the child theme installed. Right now it appears to be failing on `gulp copy-assets`

Does anyone have any ideas? Seen this before?

`npm install

> jpegtran-bin@4.0.0 postinstall /home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> gifsicle@4.0.1 postinstall /home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/understrap/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> optipng-bin@5.1.0 postinstall /home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/understrap/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> understrap@0.9.3 postinstall /home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/understrap
> gulp copy-assets

[15:23:29] Using gulpfile ~/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/understrap/gulpfile.js
[15:23:29] Starting 'copy-assets'...
[15:23:29] Finished 'copy-assets' after 15 ms
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/understrap/node_modules/undescores-for-npm/js/skip-link-focus-fix.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:313:26)
    at Glob.emit (events.js:223:5)
    at Glob.EventEmitter.emit (domain.js:475:20)
    at Glob._finish (/home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/glob/glob.js:197:8)
    at done (/home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/glob/glob.js:688:12)
    at /home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/glob/glob.js:764:12)
Emitted 'error' event on Domain instance at:
    at DestroyableTransform.EventEmitter.emit (domain.js:493:12)
    at Pumpify.emit (events.js:223:5)
    at Pumpify.EventEmitter.emit (domain.js:475:20)
    at Pumpify.Duplexify._destroy (/home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/duplexify/index.js:191:15)
    at /home/vagrant/Sites/mysite/public/wp-content/themes/understrap-child/node_modules/duplexify/index.js:182:10
    at processTicksAndRejections (internal/process/task_queues.js:76:11) {
  domainEmitter: DestroyableTransform {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { length: 0 },
      length: 0,
      pipes: [Pumpify],
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Array],
      prefinish: [Function: prefinish],
      pipe: [Function],
      data: [Function: ondata]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: false,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform],
      needTransform: true,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: null
    },
    _destroyed: false,
    _transform: [Function: forward],
    _flush: [Function: flush]
  },
  domainThrown: false
}
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.9.3 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the understrap@0.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-02-11T15_23_31_285Z-debug.log`

**Comment by axlright** [comment]
I remove understrap from the dependencies. I don't know why it's there but it doesn't make sense to me to have a project be a dependency of itself.

Remove the `understrap` dependency from `package.json` and try again.

Note I'm no expert, but this works for me so I do it.

**Comment by seanhudson** [comment]
That makes sense. I removed the understrap dependency, but it's still throwing the same error on `gulp copy-assets`

**Comment by axlright** [comment]
Okay - someone else smarter than me will need to provide insight...

**Comment by 0dp** [comment]
In the copy-assets task, have you removed the step that tries to copy the skip-link file?

**Comment by seanhudson** [comment]
I have not. Are you suggesting I should do that?

**Comment by 0dp** [comment]
Yeah because that is where it fails.

Copy-assets is looking for a file that doesn't exist. Removing that piece of code should fix it

**Comment by axlright** [comment]
I've pulled the current `master` branch and when I run `npm install` everything works great, but when I copy to a new install, I get errors looking for `gulp-babel` *but* if I copy the `package-lock.json` from the master understrap-child to the new install everything works great. This is weird for my feeble brain because I thought one wasn't supposed to transfer `package-lock.json` files and instead just keep the ones that are system generated after successful `npm install`.

Dunno if that'll help anyone else, but after like 4 hours of trying, that was the only thing that did the trick...

**Comment by nvjacobo** [comment]
> Having an unusually difficult time getting the child theme installed. Right now it appears to be failing on `gulp copy-assets`
> 
> Does anyone have any ideas? Seen this before?

@seanhudson I seen it before, in understrap child latest version 

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.9.3 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the understrap@0.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by axlright** [comment]
Yeah, I've been having that (or a similar) error constantly. Not sure if there's a fix.

**Comment by Thomas-A-Reinert** [comment]
Don´t know which but I know a [combo of those pull request](https://github.com/understrap/understrap-child/pulls) did it last time for me last time. Don´t know which but I´ll go from latest to the older ones..

**Comment by mcascardi** [comment]
Created a PR that should address this, just spend part of my day tracking down and fixing this (among other things)

**Comment by bacoords** [comment]
This has been fixed in the latest update. Please pull the latest package.json and gulp files from the repo if you're having this issue.
