### ISSUE TITLE
Overwriting archive.php or category.php doesn't take effect

### ISSUE THREAD

**Issue by teetl6** [understrap/understrap-child#253]
Hi

i need to create my own custom archive.php, but this doesn't seem to work - it still loads parent theme archive.php

I also wanted to create content-archive.php in loop-templates folder but didn't seem to work either. What's the correct solution to make archive page and category page templates?

**Comment by teetl6** [comment]
I found the solution.

I thought that problem was that theme used index.php by default. The real problem was that i had page with same slug as my category name and therefore it redirected to the wrong place.

**Comment by currentcreative** [comment]
I'm so glad I found your post. I'm guessing this is a problem for all Wordpress themes, but I don't recall ever running into it before!

Thank you for posting how you figured out the resolution. I bet it would have taken me a long time to figure that out. Looks like I had the same exact problem on my last Understrap Child website I built and it looks like I never did resolve it. I customized archive.php instead.
