### ISSUE TITLE
Popper.js removed

### ISSUE THREAD

**Issue by axlright** [understrap/understrap-child#255]
Just noticed (ha!) that `popper.js` was removed from being enqueued in `functions.php` in commit 01dcc88. Does anyone know the reason / how it's added now? Bootstrap still says that `popper.js` is required...

>Our dropdowns, popovers and tooltips also depend on Popper.js.
https://getbootstrap.com/docs/4.4/getting-started/javascript/

Thanks!

**Comment by Thomas-A-Reinert** [comment]
Ain´t it bundlet into bootstrap.bundle.js right now? The docs say:

https://getbootstrap.com/docs/4.1/getting-started/introduction/ => "_Our bootstrap.bundle.js and bootstrap.bundle.min.js include Popper, but not jQuery. For more information about what’s included in Bootstrap, please see our contents section._"

I have no clue which js get´s enqueued though and I don´t have access to my dev environment right now. And I fear even @UnderstrapFramework wouldn´t know. Or could tell why. Or what.

**Comment by UnderstrapFramework** [comment]
I think this PR is aiming to fix that?

https://github.com/understrap/understrap-child/pull/254

correct me if i'm wrong

**Comment by Thomas-A-Reinert** [comment]
As I said. You can´t tell.

**Comment by 0dp** [comment]
It looks like in the gulp tasks that its being pulled/or should be, from the node_modules and built in the scripts task. Don't know if that's broken now.

**Comment by axlright** [comment]
It looks like `bootstrap.bundle.js` does include Popper version 1.16.0 (starting at line 1579) whereas `bootstrap.js` does not. And the `gulpfile.js` compiles `bootstrap.bundle.js` so `popper.js` looks to not be needed separately.

Thanks for looking into this.

**Comment by Thomas-A-Reinert** [comment]
As I said ;)
But hey, how are you going to solve that, @UnderstrapFramework ?

**Comment by UnderstrapFramework** [comment]
Thanks @Thomas-A-Reinert il get it sorted

**Comment by Thomas-A-Reinert** [comment]
Cool. Interested in how you´re going to solve that though. But be nice to get an update on that here.

**Comment by danemorgan** [comment]
There have been several dependencies updates since this issue was raised, and a new build process is in discussion on the main theme repository. Please come take part in that conversation to assist us in finding the best, most secure process for our needs.

**Comment by bacoords** [comment]
Link to conversation for context: https://github.com/understrap/understrap/discussions/1358
