### ISSUE TITLE
LiteSpeed serving old CSS because file modification time is not updated

### ISSUE THREAD

**Issue by inthevidual** [understrap/understrap-child#257]
**Node version:** 10.19.0
**Gulp version:** 4.0.2
Hi,

I'm not sure if this is a bug or intentional, but when making changes to a live theme on a LiteSpeed server, using `gulp-watch`, by adding css to `sass/theme/_child_theme.scss`, the changes are compiled into `css/child-theme.min.css` as expected. However, because this file keeps the modification time of the file `sass/child-theme.scss`, the changes are not served.

I have verified that this is not a typical caching issue (computers/browsers that have never opened the site prior to the latest CSS modifications are still served the old CSS).

The issue disappears as soon as the modification time of `child-theme.scss` is updated.

I have created a hacky solution for this by installing `gulp-touch-cmd` and adding the following lines to `gulpfile.js`, under requirements and under the minifycss task respectively.

`var touch = require('gulp-touch-cmd');`

`pipe( gulp.dest( paths.css ) )
           .pipe(touch());`

Is this a bug that can (and should be) fixed, or am I doing something wrong here?

**Comment by Thomas-A-Reinert** [comment]
Never experienced that problem on windows with docker. Anyway – good luck with any help from the repo maintainer.

**Comment by danemorgan** [comment]
There have been several build process and dependencies updates since this issue was raised, and a new build process is in discussion on the main theme repository. Please come take part in that conversation to assist us in finding the best, most secure process for our needs.
