### ISSUE TITLE
Add new breakpoints error

### ISSUE THREAD

**Issue by andrespras** [understrap/understrap-child#258]
Hello!

I´m trying to add some new breakpoints in my child-theme but i´m getting this error in compiler: 

> Error: Invalid null operation: "null sub 0.02".
......
>>   @return if($next, breakpoint-min($next, $breakpoints) - .02, null);

I already try to import functions and grid files before $grid-breakpoints but the error still happen.

How i can solve that?

My child_theme_variables.scss:

> `// Use this file to overwrite the basic Bootstrap variables and add your own variables
> // To overwrite a Bootstrap variable you don´t have to touch the Bootstrap folder. 
> // Just copy a variable from /sass/bootstrap/_variables.scss, paste it here and edit the value.
> // As example you find one of the most important Bootstrap variable below: $brand-primary.
> // Thats the ugly Bootstrap blue used for all the links, primary buttons etc.
> // Just add your color code here, compile the theme.scss file to change this color everywhere
> 
> /* set the overriding variables */
> 
> $grid-breakpoints: (
>     xxxs: 0,
>     xxs: 320px,
>     xs: 568px,
>     sm: 667px,
>     md: 768px,
>     lg: 992px,
>     xl: 1200px,
>     xxl: 1440px,
>     xxxl: 1600px,
>   );
> 
>   $container-max-widths: (
>     xxxs: 0,
>     xxs: 320px,
>     xs: 568px,
>     sm: 667px,
>     md: 768px,
>     lg: 992px,
>     xl: 1200px,
>     xxl: 1440px,
>     xxxl: 1600px,
>   );
>   
...
> $nav-pills-border-radius:     50rem !important;
> $nav-link-padding-y:          0.6rem !default;
> $nav-link-padding-x:          1.5rem !default;`

Thanks!

**Comment by Thomas-A-Reinert** [comment]
Can you tell any use-case for that? 
Do you know what you´re trying to achieve with the code above? Your trying to define a viewport that has a MAX-WIDTH of ZERO. Honestly, please tell me a case in which you´ll find that situation.

Just interested, don´t have a solution at hand though, because the intention of the whole thing ain´t clear. Besides: This is a simply S/CSS/conceptual problem. Not an understrap-related, so I´m going to close this issue,

Feel free to reply if you got any questions.

**Comment by monolith920** [comment]
Im running into a similar issue.  Im not receiving an error but my new breakpoints and max widths are not showing up in the compiled CSS.  I have them in the child_theme_variables file and this file is getting called before bootstrap4 in child_theme.scss.  Any suggestions?

child_theme_variables.scss:
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px,
  xxl: 1600px
);

$container-max-widths: (
  sm: 540px,
  md: 720px,
  lg: 960px,
  xl: 1140px,
  xxl: 1540px
);

child_theme.scss:
@import "theme/child_theme_variables";
@import "assets/bootstrap4";
@import "assets/font-awesome";
@import "theme/child_theme";

**Comment by bacoords** [comment]
Have you tried including the functions to build the new asset sizes? Here's the sample code from Bootstrap's variables file - it includes these additional mixins, which you may want to run in your child-theme-variables (this is untested, FYI):

```scss

// Grid breakpoints
//
// Define the minimum dimensions at which your layout will change,
// adapting to different screen sizes, for use in media queries.

$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px
) !default;

@include _assert-ascending($grid-breakpoints, "$grid-breakpoints");
@include _assert-starts-at-zero($grid-breakpoints, "$grid-breakpoints");


// Grid containers
//
// Define the maximum width of `.container` for different screen sizes.

$container-max-widths: (
  sm: 540px,
  md: 720px,
  lg: 960px,
  xl: 1140px
) !default;

@include _assert-ascending($container-max-widths, "$container-max-widths");
```

**Comment by danemorgan** [comment]
Absent any indication to the contrary I think @bacoords has addressed this issue.
