### ISSUE TITLE
Where to run 'npm install' with a child theme?

### ISSUE THREAD

**Issue by nizz0k** [understrap/understrap-child#259]
So, I initially got started on the wrong foot and did most of my theme work in the understrap folder itself. I realize now that I am asking for trouble when the next US theme update comes around. I've downloaded and tried to install the child theme to port my updates over, and I realized the documentation for the child theme (which should be obvious, but isn't to noobs) isn't on the same level as the parent theme. So my question is: where do I run 'npm install': in the parent or child theme folder root? It makes more sense in the child theme, but since I'm having install problems, anyway right now, so I thought I would distract myself with asking this here?

**Comment by 0dp** [comment]
In the child theme root folder
