### ISSUE TITLE
Blank page, issue with Body attributes on Bitnami server

### ISSUE THREAD

**Issue by lukababu** [understrap/understrap-child#261]
I encountered an issue when I installed the child theme on my Amazon Lightsnail server.

The whole page appeared blank white. Upon closer inspection, it appeared that the source code stopped midway through the `<body>` tag.

After enabling the debug this is what I discovered:

`Fatal error: Uncaught Error: Call to undefined function understrap_body_attributes() in /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/st-aidan/header.php:24 Stack trace: #0 /opt/bitnami/apps/wordpress/htdocs/wp-includes/template.php(723): require_once() #1 /opt/bitnami/apps/wordpress/htdocs/wp-includes/template.php(672): load_template('/opt/bitnami/ap...', true) #2 /opt/bitnami/apps/wordpress/htdocs/wp-includes/general-template.php(41): locate_template(Array, true) #3 /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/st-aidan/index.php(17): get_header() #4 /opt/bitnami/apps/wordpress/htdocs/wp-includes/template-loader.php(106): include('/opt/bitnami/ap...') #5 /opt/bitnami/apps/wordpress/htdocs/wp-blog-header.php(19): require_once('/opt/bitnami/ap...') #6 /opt/bitnami/apps/wordpress/htdocs/index.php(17): require('/opt/bitnami/ap...') #7 {main} thrown in /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/st-aidan/header.php on line 24`

I removed `understrap_body_attributes();` and it works now, but why is this not an issue for my local RPI 3 LAMP server?

Do I lose a lot by removing that tag?
It seems to only add `itemscope itemtype="http://schema.org/WebSite` within the tag.

**Comment by bacoords** [comment]
This sounds like a server specific issue, but have you ensured that you're running both the latest parent and latest child theme on the additional server?

**Comment by lukababu** [comment]
This is no longer an issue, I don't remember what happened but I'll go ahead and close it :)
