### ISSUE TITLE
Nav Bar Won't Stay Collapsed

### ISSUE THREAD

**Issue by artinflight** [understrap/understrap-child#263]
I've been searching for hours and cannot find a solution. Running Understrap with Child Theme on Bitnami Wordpress on AWS.

Navbar collapse button can open navbar, also closes but as soon as it's closed it opens again.

Not sure what I need to share for assistance but the site is visible at http://ontarioppe.com

Tried gulp scss-for-prod which I found in another thread but got the following error:
` Task 'scss-for-prod' is not in your gulpfile`

**Comment by bacoords** [comment]
If this is still an issue, please respond with a functioning link. If not, we'll close the issue after a few days.

One note `scss-for-prod` is a task in the parent theme, but not here in the child theme.
