### ISSUE TITLE
Trying to update scss on child theme with Prepros

### ISSUE THREAD

**Issue by elias90** [understrap/understrap-child#267]
Hi there, i'm developing a new Wordpress with Understrap project using Local, and prepros to compile scss.

It's the first time that I use this and I have some problems.

I install prepros, upload the child theme folder, make the changes in the _child_theme.scss like this > https://share.getcloudapp.com/JrubemER

After that, prepros compile the file correctly but when I reload the page the changes will no make effect.

I control the ./css/theme.min.css and the primary variable have the same default color.

Can you help me please?

**Comment by danemorgan** [comment]
Are you using the child theme from this repository or one of the premium child themes?

If you are using the one from this repository, Prepros is the wrong tool to use.

There is an entire NPM build process built into the child theme for you to use.

Please see the [Read Me](https://github.com/understrap/understrap-child/blob/main/README.md) for instructions for using this.
