### ISSUE TITLE
Add note to README document

### ISSUE THREAD

**Issue by pdmwu** [understrap/understrap-child#269]
Thanks for the hard work on this theme. I have now worked with it for some months, and I just learned that custom Javascript needs to go into the /src/js/ folder. The readme file just states how to work with SCSS files. It would be great if you could add a describing paragraph to the README markdown document so that starters can find their way easier to that location. Perhaps also put a line there where to put images.

**Comment by bacoords** [comment]
This has been done. 

We don't have any image processes, so you're free to create your own directory.
