### ISSUE TITLE
understrap-child error functions.php

### ISSUE THREAD

**Issue by danieldevos** [understrap/understrap-child#270]
Hi,
I use the understrap-child theme and my editor has several 
Undefined function in the functions.php file of the child theme 
Are you aware of this problem?

Thank you in advance for your help 

Dan

**Comment by 0dp** [comment]
Could you elaborate with some examples?

**Comment by danieldevos** [comment]
Thanks for the answer but I noticed that the error comes from my editor and not from the child theme. 

Regards

**Comment by 0dp** [comment]
No worries, please close the issue if it's resolved 👍

**Comment by danieldevos** [comment]
Thanks
