### ISSUE TITLE
Yoast SEO Title broken on Homepage

### ISSUE THREAD

**Issue by EllieMaffio93** [understrap/understrap-child#274]
Hi,

I recently switched theme on my Wordpress website. I'm now using Understrap with Understrap-Child. 
Everything works fine, except for the Yoast SEO title on the Homepage which appears to be broken.

According to Yoast settings, the title should be **Libri | Letture.org**
But when I look for my website in Google this is what I see: **Letture.org: Libri**

Up until the switch of the theme, everything worked fine, but right after the switch the SEO title broke.
This is the second time I've noticed this issue. It happened on another website I worked on with Understrap/ Understrap-Child.

Is there a way of fixing this?

Thanks for your help.
Kind regards,

Eleonora

**Comment by bacoords** [comment]
This has been updated. Make sure you pull the latest version of Understrap from the theme repo and let us know if that's good.
