### ISSUE TITLE
Google Fonts - do I need to do something more than putting them in /fonts?

### ISSUE THREAD

**Issue by currentcreative** [understrap/understrap-child#288]
I put the new Google Fonts I downloaded into the same folder as the font awesome fonts and adjusted the CSS accordingly (for example `font-family: 'Open Sans', sans-serif;`) but the Google fonts are not showing up.

**Comment by danemorgan** [comment]
Did you add the @font-face declarations for the fonts?

**Comment by currentcreative** [comment]
Wow, that was fast! Nope, I'm a moron. Thanks. I've been directly linking Google Fonts for so long, I completely forgot about that. And how to do it. I'll have to go Googling to figure it out again. Just decided to do it this time since FontAwesome was already downloaded into the Understrap, so I figured I'd try to go the extra mile this time myself.

**Comment by danemorgan** [comment]
CSS Tricks has a pretty good refresher on it.

https://css-tricks.com/snippets/css/using-font-face/

**Comment by currentcreative** [comment]
Thank you again!
