### ISSUE TITLE
How to get excerpt on custom front-page.php template?

### ISSUE THREAD

**Issue by currentcreative** [understrap/understrap-child#290]
I've been looking through the inc/setup.php code and I can see the excerpt filters are in there, but I can't seem to get it working on my homepage template front-page.php.

Understrap's default blog posts page uses **index.php** which pulls in l**oop-templates/content.php** which just uses `<?php the_excerpt(); ?>` to show the excerpt. 

But, when I put <?php the_excerpt(); ?> on the homepage, it shows nothing. I tried `wp_reset_query();` and `wp_reset_postdata();` after the main loop that grabs the homepage content, but it had no effect.

**Comment by danemorgan** [comment]
I think we're going to need to see some of your code to sort this out.
