### ISSUE TITLE
custom code folder structure

### ISSUE THREAD

**Issue by joaquiboy** [understrap/understrap-child#296]
I just want to ask if there are documentations on how we can folder structure our custom codes base on understrap recommended practice in child theme. if you're getting confused about what I mean, it's just we want to break the files and not relying on a single file to put the entire code for all modifications, then we want to hook that certain PHP file into a single file template to make it more organized.

thank you

**Comment by bacoords** [comment]
Please see [discussion #1403 here](https://github.com/understrap/understrap/discussions/1403#discussioncomment-1291232) for more on this topic.
