### ISSUE TITLE
Custom Child Scripts and compiling child-theme.js

### ISSUE THREAD

**Issue by jameskrill** [understrap/understrap-child#30]
Here is what I see happening: 

1. In /inc/enqueue.php 'understrap-scripts' is being dequeued and deregistered, and replaced with 'child-understrap-scripts' (which is /js/child-theme.min.js')
2. In gulpfile.js, that script is NOT being compiled, like it is in the parent theme (understrap). See in the "watch" task - it is not watching .js files or running "scripts" like it is in the parent theme. 
3. Therefore, if the scripts in the task "scripts" ever change, the child theme will never pick those up. If that was intended, it seems as if you can remove the "scripts" task from the child-theme's gulpfile. Or replace it with stub for including custom js files and include a watch task in the "watch" task for compiling custom scripts... right?

**Comment by jimkrill** [comment]
There's not really any mention of how best to include custom scripts into the child-theme. 
What are your thoughts on this? 

I could see a couple options:
1. Keep custom scripts out of compiled scripts and just enqueue them as needed (wp_enqueue_script)
2. Build into gulpfile.js some tasks for compiling custom scripts from a source folder and load them globally in the enqueue.php file.

**Comment by jimkrill** [comment]
Something like this in the child theme's gulpfile:

```javascript
gulp.task('custom-scripts', function() {
   var scripts_array = [
       // Custom Scripts
       './js/src/main.js',
   ];
    gulp.src(scripts_array)
       .pipe(concat('custom-scripts.min.js'))
       .pipe(uglify())
       .pipe(gulp.dest('./js/'));

    gulp.src(scripts_array)
        .pipe(concat('custom-scripts.js'))
        .pipe(gulp.dest('./js/'));

});
```

And adding a watch to the 'watch' task:
```javascript
gulp.task('watch', function () {
    gulp.watch('./sass/**/*.scss', ['sass']);
    gulp.watch('./css/child-theme.css', ['cssnano']);
    gulp.watch([basePaths.dev + 'js/**/*.js'], ['scripts']);
    gulp.watch('./js/src/**/*.js', ['custom-scripts']);
});
```

I added a '/src/' folder to the '/js/' folder because the './src/' folder is generated from the 'copy-assets' task. Made sense to me... any thoughts?

Also, I added the 'scripts' task back into 'watch' - to pick up any updates to the ./src/js/ files... thoughts?

**Comment by jimkrill** [comment]
And then the last piece being adding the wp_enqueue_script() to the ./inc/enqueue.php file:

```php
// Custom Global Scripts
  wp_enqueue_script( 'custom-child-understrap-scripts', get_stylesheet_directory_uri() . '/js/custom-scripts.min.js', array(), $the_theme->get( 'Version' ), true );
```

**Comment by jimkrill** [comment]
One last thing... a suggestion to not repeat yourself when defining the scripts that go into child-theme.min.js and child-theme.js (could also be applied to parent theme):

Here is the original:
```javascript
// Run:
// gulp scripts.
// Uglifies and concat all JS files into one
gulp.task('scripts', function() {
  gulp.src([
    basePaths.dev + 'js/owl.carousel.min.js', // Must be loaded before BS4
    basePaths.dev + 'js/tether.js', // Must be loaded before BS4

    // Start - All BS4 stuff
    basePaths.dev + 'js/bootstrap4/bootstrap.js',

    // End - All BS4 stuff

    basePaths.dev + 'js/skip-link-focus-fix.js'
    ])
    .pipe(concat('theme.min.js'))
    .pipe(uglify())
    .pipe(gulp.dest('./js/'));

  gulp.src([
    basePaths.dev + 'js/owl.carousel.min.js', // Must be loaded before BS4
    basePaths.dev + 'js/tether.js', // Must be loaded before BS4

    // Start - All BS4 stuff
    basePaths.dev + 'js/bootstrap4/bootstrap.js',

    // End - All BS4 stuff

    basePaths.dev + 'js/skip-link-focus-fix.js'
    ])
    .pipe(concat('theme.js'))
    .pipe(gulp.dest('./js/'));
});
```

And here it is with a defined array:

```javascript
// Run: 
// gulp scripts. 
// Uglifies and concat all JS files into one
gulp.task('scripts', function() {
    var scripts = [
        basePaths.dev + 'js/owl.carousel.min.js', // Must be loaded before BS4
        basePaths.dev + 'js/tether.js', // Must be loaded before BS4

        // Start - All BS4 stuff
        basePaths.dev + 'js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        basePaths.dev + 'js/skip-link-focus-fix.js'
    ];
  gulp.src(scripts)
    .pipe(concat('child-theme.min.js'))
    .pipe(uglify())
    .pipe(gulp.dest('./js/'));

  gulp.src(scripts)
    .pipe(concat('child-theme.js'))
    .pipe(gulp.dest('./js/'));
});
```

Unless there is a specific reason to repeat the arrays of those files?

There may be an even cleaner way to do this using gulp, but I'm relatively new to it and am unsure (like if you could just do both scripts in one chain).

**Comment by holger1411** [comment]
Hi!
I add the script task to the watcher task, too. Like in parent themes gulpfile.
And simplyfy the script task like you recommend it in both projects.

Thx for taht!

Just add your custom JS file and path to the "gulp script" task.

The problem with an extra "custom-scripts" task is:
Its important to controll the compiling sequence. 
For example the tether script must be added BEFORE the bs4 js, the skip to content js at the end etc.

It may be necessarry to add some custom code before or after a certain code snipped.
So you need a "custom-scripts-before" and a "custom-script-after" task...so it may be easier to just add your custom JS´s path to the "gulp scripts" task.

**Comment by Thomas-A-Reinert** [comment]
According to my experience that should have been resolved by now. Anyway: No follow ups for about 1 1/2 yrs so i´ll close that for housekeeping..
