### ISSUE TITLE
"gulpfile not found" error

### ISSUE THREAD

**Issue by rahuldhangar** [understrap/understrap-child#301]
I am unable to use gulp for compiling the scss files because when I do gulp watch, it says: "no gulpfile found"

I am using the latest version of Understrap (v 1.0.0)

Any help is highly appreciated.

**Comment by 0dp** [comment]
Hi there,

Understrap has moved to rollup.js

Look in package.json for available commands

**Comment by rahuldhangar** [comment]
Thanks @0dp 
I'm checking rollup.js docs to find more about it.
https://rollupjs.org/guide/en/#quick-start

**Comment by 0dp** [comment]
@rahuldhangar the readme file also have a getting started guide 👍
