### ISSUE TITLE
src/sass/theme/_child_theme.scss does not work

### ISSUE THREAD

**Issue by newmrxu** [understrap/understrap-child#302]
I edit this file src/sass/theme/_child_theme.scss, but nothing happens. I added Extra CSS in Theme Customizer, and it works, but no codes have been written to src/sass/theme/_child_theme.scss as well.

**Comment by bacoords** [comment]
After editing a scss file, you need to run the command line tools that compile the new CSS. SCSS files can't be edited on a server but are meant for local development. 

Check the https://github.com/understrap/understrap-child#readme for more info and let us know if this answers your questions.
