### ISSUE TITLE
feature/bs5-development / Uncaught ReferenceError: process is not defined createPopper.js:81

### ISSUE THREAD

**Issue by Piirka** [understrap/understrap-child#313]
Hi,

I get error below in the console when I am clicking simple dropdown button. Dropdowns in narbar are working fine.
```
Uncaught ReferenceError: process is not defined createPopper.js:81
```

On the line 81 is following code.
```
if (process.env.NODE_ENV !== "production") {
```

How to handle those variables? I have Windows 10 enviroment.

**Comment by bacoords** [comment]
Thanks - this appears to be an issue in the upcoming BS5 release for parent and child theme. I'll post back here once it's fixed 👍

**Comment by bacoords** [comment]
Please pull the changes (you'll need to re-run `npm install` and then `npm run js`) and let me know if it's working.

**Comment by Piirka** [comment]
Dropdowns are back to live. Thanks for this fix. 👍
