### ISSUE TITLE
NPM warnings on npm install

### ISSUE THREAD

**Issue by DLX23** [understrap/understrap-child#322]
i downloaded fresh new understrap child and do npm install, result is:
`npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'understrap-child@1.1.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.18.0', npm: '8.3.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'globby@12.0.2',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.18.0', npm: '8.3.0' }
npm WARN EBADENGINE }
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1

added 616 packages, and audited 617 packages in 29s

72 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities`

is there anything wrong? i use Latest LTS Version: 16.13.2 (includes npm 8.1.2)

**Comment by bacoords** [comment]
The only issue I see is that it's seeing your node version as lower than 16: 

`npm WARN EBADENGINE current: { node: 'v12.18.0', npm: '8.3.0' }`

**Comment by DLX23** [comment]
i installed node again now it works. thank you
