### ISSUE TITLE
Error on NPM run watch

### ISSUE THREAD

**Issue by DLX23** [understrap/understrap-child#323]
i use npm run watch and get following error
`npm run watch

> understrap-child@1.1.0 watch
> npm-run-all --parallel watch-run-*

> understrap-child@1.1.0 watch-run-css
> nodemon --watch src/sass/ --ext scss --exec "npm-run-all css"

> understrap-child@1.1.0 watch-run-js
> nodemon --watch src/js/ --ext js --exec "npm-run-all js"

[nodemon] 2.0.15
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\js\**\*
[nodemon] watching extensions: js
[nodemon] watching path(s): src\sass\**\*
[nodemon] watching extensions: scss
[nodemon] starting `npm-run-all js`
[nodemon] starting `npm-run-all css`

> understrap-child@1.1.0 css
> npm-run-all css-compile css-postcss css-minify

> understrap-child@1.1.0 js
> npm-run-all js-compile js-minify

> understrap-child@1.1.0 css-compile
> sass --style expanded --source-map --embed-sources --no-error-css --quiet src/sass/child-theme.scss:css/child-theme.css src/sass/custom-editor-style.scss:css/custom-editor-style.css

> understrap-child@1.1.0 js-compile
> rollup --config src/build/rollup.config.js --sourcemap

M:\work\bbs_center\src\js\bootstrap.js, M:\work\bbs_center\src\js\skip-link-focus-fix.js, M:\work\bbs_center\src\js\custom-javascript.js → js\child-theme.js...
created js\child-theme.js in 3s

> understrap-child@1.1.0 js-minify
> terser --config-file src/build/terser.config.json --output js/child-theme.min.js js/child-theme.js

> understrap-child@1.1.0 css-postcss
> postcss --config src/build/postcss.config.js --replace "css/*.css" "!css/*.rtl*.css" "!css/*.min.css"

(node:23624) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:720:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
ERROR: "css-postcss" exited with 1.
ERROR: "css" exited with 1.
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] clean exit - waiting for changes before restart`

i use Latest LTS Version: 16.13.2 (includes npm 8.1.2)

**Comment by bacoords** [comment]
can you run `node -v` and `git -v` and paste the results here?

**Comment by DLX23** [comment]
i installed node again now it works. thank you
