### ISSUE TITLE
How to get tooltips working?

### ISSUE THREAD

**Issue by MastaBaba** [understrap/understrap-child#328]
I just tried to get a tooltip to work as per the BS5 docs:

https://getbootstrap.com/docs/5.1/components/tooltips/#example-enable-tooltips-everywhere

```
var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
  return new bootstrap.Tooltip(tooltipTriggerEl)
})
```

But, the above results in a console error:

`ReferenceError: Can't find variable: bootstrap`

How to get tooltips to work?

**Comment by bacoords** [comment]
Hey, we're discussing this on this thread over here: https://github.com/understrap/understrap/issues/1583 See the comments for some ideas

**Comment by MastaBaba** [comment]
Thanks @bacoords. I had searched for 'tooltip' in the list of issues.
