### ISSUE TITLE
Updates to scss in Siteground File Manager don't pass through to website

### ISSUE THREAD

**Issue by cander1089** [understrap/understrap-child#329]
Hello,

I have made several changes to the understrap-child theme scss to override Bootstrap 5 defaults. Unfortunately none have passed through to the site.

FWIW I use Siteground as a host and have been updating the files in their File Manager.

Thank you for the help!
Chris

**Comment by bacoords** [comment]
The scss files themselves must be compiled into the main css file. This is typically done in your local environment using the build process bundled with the child theme. For more details check this out: https://docs.understrap.com/#/understrap-child/npm

**Comment by bacoords** [comment]
Correct, you want to set up a local development environment for building out those assets.

**Comment by bacoords** [comment]
Closing this - please re-open if you need anything else!
