### ISSUE TITLE
Bootstrap styles in the block editor

### ISSUE THREAD

**Issue by briandeer** [understrap/understrap-child#337]
I've developed some custom blocks [using ACF](https://www.advancedcustomfields.com/resources/blocks/) for my child theme. I'm using bootstrap 5 grid columns in the files. Unfortunately, my bootstrap 5 grid styles don't show up in the block editor but do show up on the front end of the site. Am I doing something wrong or should I be using the styles recommended for the block editor instead of bootstrap columns when developing custom blocks?

**Comment by bacoords** [comment]
That's correct, we don't import ALL of bootstrap into the block editor, just some of it. You could import any extra pieces from bootstrap in custom-editor-styles.scss

**Comment by briandeer** [comment]
Ah.. good idea. That worked perfectly. Thank you so much for your quick response, Brian. Have a fantastic day!!
