### ISSUE TITLE
sass/assets/bootstrap4.scss has wrong dependency 

### ISSUE THREAD

**Issue by mxp83** [understrap/understrap-child#34]
On line 27 it initially says
@import "../../src/sass/bootstrap4/animation";

which will break gulp watch when updating sass files:
```
Plumber found unhandled error:
 Error in plugin 'gulp-sass'
Message:
    sass/assets/bootstrap4.scss
Error: File to import not found or unreadable: ../../src/sass/bootstrap4/animation
       Parent style sheet: /Users/riverrockmarketing/localdev/www/local.riverrock/htdocs/wp-content/themes/casino-understrap-child/sass/assets/bootstrap4.scss
        on line 27 of sass/assets/bootstrap4.scss
>> @import "../../src/sass/bootstrap4/animation";
   ^

Details:
    status: 1
    file: /Users/riverrockmarketing/localdev/www/local.riverrock/htdocs/wp-content/themes/casino-understrap-child/sass/assets/bootstrap4.scss
    line: 27
    column: 1
    formatted: Error: File to import not found or unreadable: ../../src/sass/bootstrap4/animation
       Parent style sheet: /Users/riverrockmarketing/localdev/www/local.riverrock/htdocs/wp-content/themes/casino-understrap-child/sass/assets/bootstrap4.scss
        on line 27 of sass/assets/bootstrap4.scss
>> @import "../../src/sass/bootstrap4/animation";
   ^
```

it should be:
@import "../../src/sass/bootstrap4/transitions";

**Comment by mxp83** [comment]
It is also affecting line 37:
`@import "../../src/sass/bootstrap4/tags";`

should be:
`@import "../../src/sass/bootstrap4/badge";`

**Comment by holger1411** [comment]
Hi!
no, seems you update the dependency to Bootstrap 4 Alpha 6, but keep the old sass/assets/bootstrap4.scss from UnderStrap Child 0.1.7 (or older)

The /animation subfolder was kicked/renamed from A5 to A6. Make sure you use this file:
https://github.com/holger1411/understrap-child/blob/master/sass/assets/bootstrap4.scss

Here you can see the changes:
https://github.com/holger1411/understrap-child/commit/689e371cd0b6170a0493edc05801e3d3a359d815#diff-dd6dab4f5100478669aa7bcef5135bed

**Comment by jznadams** [comment]
Maybe it would be a good idea for "gulp copy-assets" to delete the existing src folder as a first step? I just found a bunch of obsolete files lingering in my directory after trying to update the child theme.

**Comment by holger1411** [comment]
Good idea!
I add a task which runs automatically before "gulp copy-assets". It delets any file inside the /src folder:
https://github.com/holger1411/understrap-child/commit/32fdfc8a74afe7db896497ef196800cc4defd0f4

I also add the same task to the parent
