### ISSUE TITLE
Accordion do not close after being open

### ISSUE THREAD

**Issue by dantahoua** [understrap/understrap-child#340]
Accordion close only if opening another child. But clicking on the same one to close it do not work...
Even tried with regular html from the boostrap website, seems something change the behavior in Understrap...

**Comment by bacoords** [comment]
Can you provide more information and potentially some sample code? What version of udnerstrap child do you see in the package.json? What is the code you're using?

**Comment by dantahoua** [comment]
You can see it in action there: http://delacite.lesaintdev.com/notre-ecole/
The same code is used on another website without any problem. I even tested it with the sample code from Bootstrap website, no more luck... Weird...

**Comment by kirannasim** [comment]
@dantahoua this is really weird. I just tested with your accordion HTML on my local, it works well with expand/collapse.
I installed the fresh WP and installed Understrap / Understrap Child theme.

![image](https://user-images.githubusercontent.com/11325580/156825218-dfbebc76-eb31-43e3-aabc-dbec71bad294.png)

I can see many js libraries are loading on your site. Any js can affect the accordion expand/collapse. If you can share WP Admin to my email(kiran.nasim@howarddc.com), I will fix this issue. 

![image](https://user-images.githubusercontent.com/11325580/156825608-1b5c2069-c0c4-4e63-bf35-2de2cd6490ce.png)

**Comment by dantahoua** [comment]
Ok so you think it's compatibility problem with another library. Interesting, should be easy to find as I use exact same code on another website, but with slightly different plugin along side. I'll check and come back to you. Will send you admin credential if I do not find it. :)

**Comment by dantahoua** [comment]
Finaly, not more luck by removing all plugin. Also removed my custom JS code, no more luck. This problem drive me nut!

**Comment by kirannasim** [comment]
@dantahoua Please close this issue if you're all good here.
