### ISSUE TITLE
I know this is my own ignorance, but I can not get a Bootstrap 5 sticky footer to work with the lastest Understrap-Child

### ISSUE THREAD

**Issue by currentcreative** [understrap/understrap-child#353]
Shouldn't I be able to just follow this example? https://getbootstrap.com/docs/5.0/examples/sticky-footer-navbar/

Serious question, too: why does anybody not use a sticky footer by default? Nobody really wants footer content in the middle of a page if there isn't enough content to push it down, do they?

**Comment by bacoords** [comment]
Ha yeah, the sticky footer feels like it should be a browser default.

Did you use the `.mt-auto` class on the footer and the `.h-100` class on the `<html>` and `<body>` elements?

**Comment by currentcreative** [comment]
Thank you for explaining what the problem is. Part of the problem was my unfamiliarity with Bootstrap 5 (I was using the wrong classes in the wrong places), but now that you've given me the solution, I have to figure out how to do that without breaking the other body tags. 

This does not feel very user-friendly:

`<body <?php body_class(); ?> <?php understrap_body_attributes(); ?>>`

I need to open the whole Understrap parent theme to track down these functions and copy them into Understrap-Child just to add some classes. That's feels unwieldy, not tidy, in my opinion.

**What I ended up doing earlier today which also worked was this:**

```
#page { /* parent element of .sticky-footer */
  min-height: 100vh;
}
.sticky-footer {
  position: sticky;
  top: 100%;
  background: rgb(233, 233, 233);
}
```
I'd rather not adding more CSS than necessary, so I will now go research how to add body classes without breaking the Understrap `body_class()` function. I'm guessing you add more classes in `understrap_body_attributes()`.

**Comment by bacoords** [comment]
Here's what I did in header.php:

`<html class="h-100" <?php language_attributes(); ?>>`

`<body <?php body_class( 'h-100' ); ?> <?php understrap_body_attributes(); ?>>`

`<div class="site h-100 d-flex flex-column" id="page">`

And then footer.php:
`<div class="wrapper mt-auto" id="wrapper-footer">`


The main issue is that the footer sits inside the #page wrapper so we have to adjust for that.

**Comment by engAhmad** [comment]
just add class "**fixed-bottom**" to the footer element 

`<footer class="footer fixed-bottom"></footer>`

**Comment by bacoords** [comment]
To be clear, the `fixed-bottom` class will keep the footer on the bottom even after scrolling, which is slightly different than pushing the footer to the bottom on pages with little to no content.

**Comment by currentcreative** [comment]
bacoords, thanks for your hard work helping me out here. And you're right, `fixed-bottom` is a whole different thing. That's basically a bottom banner style footer which is good for a call to action promoting a sale or something, but very odd for a footer design otherwise.

It's a shame this is so difficult with just Bootstrap classes. I'll share with you my simpler approach that just took a couple lines of CSS:

```
#page { /* parent element of .sticky-footer */
  min-height: 100vh;
}
.sticky-footer {
  position: sticky;
  top: 100%;
  background: #262626;
  color: white;
  padding: 125px 175px; /* this is a really tall footer just to make the point that it does not affect sticky layout. You can  remove this padding and the footer will still stick to the bottom no problem. */
}
```

**Comment by engAhmad** [comment]
above approach pushing  content with the footer to bottom leaving huge gap on top of the content !

**header.php**
```
<html class="h-100" <?php language_attributes();?>>

<body <?php body_class();?> <?php understrap_body_attributes();?>>

<div class="site h-100" id="page">
```

**functions.php** 

**keep default classes** 

```
/**
 * add required classes for sticky footer
 */
function sticky_footer_body_class($classes)
{
    $array = array('d-flex', 'flex-column', 'h-100');

    return array_merge($classes, $array);
}
add_filter('body_class', 'sticky_footer_body_class');
```
**footer.php**

`<div class="wrapper mt-auto" id="wrapper-footer">`

**Comment by currentcreative** [comment]
Not sure if you're talking about my code, but there's no gap. I had to match a Squarespace site exactly and this got me there. No gap. They have a huge footer and it's colored dark grey. I didn't include the background color in the above code, because it has nothing to do with the sticky-footerness of it. You can just remove the gigantic padding to remove the space if you don't want a huge footer area.
