### ISSUE TITLE
Changes to 'custom-editor-style.css' not reflected in 'custom-editor-style.min.css'?

### ISSUE THREAD

**Issue by dekkydog** [understrap/understrap-child#365]
Hi there, maybe I'm missing something.... but If one tries to customise the 'css/custom-editor-style.css' then run 'npm run css' any additional custom styles get stripped and do not make it to the 'custom-editor-style.min.css'? Therefore they not implemented in the wp-admin.

This has been an issue for me since I started using the understrap child theme V1.1.0. 

I got around the issue by simply enqueueing my own admin stylesheet.

Is this expected behaviour?

**Comment by bacoords** [comment]
Yes basically. You should add your custom css to the original SCSS file: 

https://github.com/understrap/understrap-child/blob/main/src/sass/custom-editor-style.scss

Then when you run the `npm run css` command, you'll see the code from the .scss file show up.

**Comment by dekkydog** [comment]
Doh! How the hell did I miss that. Thanks @bacoords  :-)
