### ISSUE TITLE
navbar-branding.php strips out my HTML somehow

### ISSUE THREAD

**Issue by currentcreative** [understrap/understrap-child#388]
I'm not sure how or why but, this **"logo-wrapper" div** I added in `navbar-branding.php` gets stripped right out completely. It is nowhere to be found in the page source. Is there a way I can make Understrap **not** strip this out?

```
<div id="logo-wrapper">
  <h1 class="navbar-brand mb-0">
    <a rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>" itemprop="url">
      <?php bloginfo( 'name' ); ?>
    </a>
  </h1>
</div>

```

**Comment by wpbuilds** [comment]
Have you checked the conditional statements above your #logo-wrapper ID within that file? If you cannot see your wrapping div in the page source it's likely that one of these conditional statements is preventing it from showing where you are expecting to see it? Understrap does not strip this from your HTML. Hope that helps :-)

**Comment by currentcreative** [comment]
Yes, but thank you for pointing it out and causing me to check again!

I was working on the front-page.php and didn't have a custom logo, so I thought I was reading those conditional statements correctly. Just now I realized that **&& is_home()** does not apply to my situation. For some reason I always see "is_home()" and just think, "duh, yup, front-page.php my home page alright!"

**Comment by wpbuilds** [comment]
Glad that was useful!
