### ISSUE TITLE
input-group-addon stays gray

### ISSUE THREAD

**Issue by str** [understrap/understrap-child#40]
I changed the CSS primary color and create a button with the class `input-group-addon btn btn-primary` but the button stayed gray.

**Comment by holger1411** [comment]
Hi! 
The input group markup with a primary button should looks like this:
```
<div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-primary" type="button">Go!</button>
      </span>
      <input class="form-control" placeholder="Search for..." type="text">
   </div>
```

It works on the demo site:
https://understrap.com/understrap/?page_id=1817

The button uses the changed primary color
