### ISSUE TITLE
How to enable carousel indicators to hero?

### ISSUE THREAD

**Issue by josephlariosa** [understrap/understrap-child#44]
Hi Holger!

STUPID question here.

I got the indicators running after pasting it to hero.php

```
 <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>

```

the problem is that it does not switch the active class

Kindly answer my stupidest question ever hehehe.

**Comment by mohamedaitbella** [comment]
it's not a stupid question I have the same problem and I don't know how to integrate indicators dynamically to detect the number of images and generate indicators

**Comment by Thomas-A-Reinert** [comment]
No follow ups for more than 1 1/2 yrs, so I guess that has been resolved by now.
