### ISSUE TITLE
Got problems with child-theme

### ISSUE THREAD

**Issue by christian70** [understrap/understrap-child#49]
Hi. I'm working on Understrap for the first time, it seems to be one of the best WP starter theme. I installed the understrap theme, and it works just fine. The css file is correctly compiled and added to the test site. Every new CSS rule added to that is compiled as well. The problem occurs when I try to use the child-theme: I followed all instructions on [https://github.com/holger1411/understrap-child](url) but custom CSS rules written in sass/theme/understrap-child.scss don't effect on main css file. It seems they are not compiled at all. I'm using grunt watch-bs pointing to the folder of understrap parent theme (as indicated in docs)...  What am I doing wrong? Quite frustrating, sorry...

**Comment by christian70** [comment]
Ok, I follow step-by-step this article [https://github.com/holger1411/understrap/issues/15](url) and re-installed all. Now it seems to work fine, even if compiling is a bit slow process. I would say that instructions [()](https://github.com/holger1411/understrap-child) about installing and developing on child theme are not very clear, though. For example, you must browse to the location of your UnderStrap CHILD THEME  copy not your UnderStrap as written.

**Comment by holger1411** [comment]
Hi!
The child theme use the parent theme as dependency and copies the need files from it to its own /src folder...so its not wrong...but you are right, it can be misleading...

**Comment by kthurm** [comment]
Hi-
I'm having the same problem with the making css changes to the child theme, but the above didn't answer my question.
As instructed, I'm making changes to sass/theme/_child_theme.scss

I'm using Gulp.
It looks like it is working:

$ gulp watch
[16:46:55] Using gulpfile ~/Local Sites/angier-performance-works/app/public/wp-content/themes/understrap-child/gulpfile.js
[16:46:55] Starting 'watch'...
[16:46:55] Finished 'watch' after 26 ms
[16:47:03] Starting 'sass'...
[16:47:04] Finished 'sass' after 643 ms
[16:47:04] Starting 'minify-css'...
[16:47:04] Finished 'minify-css' after 341 ms

But I don't see any changes. I've been adding very basic things like 
h1 {display:none;} just to see if it will work. 

I have used this theme before (and love it!) but I've never been able to get the styles to work correctly. Last time I just added a new css file.

Any help would be appreciated!
Thanks!

**Comment by jrglass** [comment]
@kthurm, I was having the same issues as you state.

I updated brew and made sure I was running all the latest versions, globally, of npm, node.js and gulp.

Then I starting with a fresh wordpress install, adding the understrap theme, then adding the understrap-child theme.

From there I ran `npm install` then `gulp copy assets` within the child theme folder. I'm not running browser sync though.

After I did all that it started working just fine. I just have to refresh the browser, which is the least of my worries.

Sometimes you just have to start fresh...

**Comment by kthurm** [comment]
Thanks @jrglass. Downloaded latest versions of everything (including understrap-child theme). It's still not working.

11:11:12] Using gulpfile ~/Desktop/local_sites/apw/app/public/wp-content/themes/understrap-child/gulpfile.js
[11:11:12] Starting 'watch'...
[11:11:12] Finished 'watch' after 20 ms
[11:12:34] Starting 'sass'...
[11:12:34] Finished 'sass' after 865 ms
[11:12:34] Starting 'minify-css'...
[11:12:34] Finished 'minify-css' after 3.59 ms
[11:13:12] Starting 'sass'...
[11:13:12] Starting 'minify-css'...
[11:13:12] Finished 'minify-css' after 2.98 ms

**Comment by holger1411** [comment]
@kthurm: Can you find the changes in your css/child-theme.css file?
Just to find out if it is a compiling or a browser issue.
And: Do you use anykind of Caching Plugin on your working WP install?

**Comment by kthurm** [comment]
Thanks @holger1411 
Yes it does change understrap-child/css/child-theme.css but not understrap-child/css/child-theme.min.css.
I'm not using a caching plugin on WP.
Thanks!

**Comment by jonnycyr** [comment]
I'm running into the same exact issue, I'm also not using a caching plugin on WP. I'm running wordpress by using vccw: http://vccw.cc/

**Comment by holger1411** [comment]
Okay the problem seems to be that the watcher task starts the sass task and the minify task right after it. If the sass task is not fast enough the minify task just find the old css file which did not include the changes and minifies that. After it the sass task is finished. But then the old css file was already minified.
That would explain why it happens sometimes and by some people, but not for everyone.

I´am currently playing around with the gulp package "run-sequence" and "gulp-sequence", which let you build more complexe tasks. 
Will release it as soon as possible

**Comment by GU8187** [comment]
Hi there and congratulations for the great work,

Infortunately I cant get child theme css modification to work either

I had small Incompatible units: 'rem' and 'px*rem'  on line 444 of src/sass/bootstrap4/_variables.scss to deal with also

My try was to create simple css blocks like
.bloc {
  padding-top: 15px;
}
in /understrap-child/sass/theme/_child_theme.scss

I went through topic with gulp watch-bs issues, so I change the task order to put browser-sync at the end of task list
but I can't find a workaround
I updated to latest stable release of theme though

**Comment by Thomas-A-Reinert** [comment]
This issue is about one year old now and i know all of the above issues have been fixed by now. Closing it for housekeeping. Feel free to reopen if needed.

**Comment by paarami** [comment]
Hi,
Please reply which file (location) to use for custom css

**Comment by bacoords** [comment]
The documentation has a great walkthrough of the build process and where to edit css/js: https://docs.understrap.com/#/understrap-child/npm
