### ISSUE TITLE
Query Custom Post Types and Add Pagination

### ISSUE THREAD

**Issue by barnettj7** [understrap/understrap-child#5]
Hi, 

I am trying to use the main query to query custom post types and taxonomies, and add pagination to the custom post type pages. Is this possible with the main query, or will I have to create a function and query the posts using wp_query?

Can you please provide me with a code example and steps on how you would complete this?

Thanks,

JB

**Comment by holger1411** [comment]
Hi!
Sorry, I can´t code this for you. Its a general WordPress questions and not UnderStrap related.
But basically I would define a custom post type in your functions.php and than query it within the loop.
A good article can be found here:
https://codex.wordpress.org/Post_Types

**Comment by barnettj7** [comment]
I have already registered the post types and created a wp_query. The question is more to do with pagination, which I understand may be a general wordpress question. 

Do you have any referrence to pagination. I have read the codex, but it doesn't explain very well how to get the wp_query to paginate that post type.

Any help is appreciated. I really like using your theme and use it as a base for all of my projects. 

Thanks so much,

JB

**Comment by barnettj7** [comment]
This is some code I have found and think is on the right track for what I am trying to accomplish, but does not include pagination. I believe that you need to declare some of theses things in the functions, but not sure where to start specifically item 1, 2.


Again this is code I found, I currently only have the basic query and args in my version. I thought you may be able to point me in the right direction hopefully!


**Full Code.)**
        <?php

        $args = array(
            'post_type' => 'testimonials',
            'order' => 'DESC',
            'orderby' => 'date',
            'showposts' => 8
        );

        if (get_query_var('cat_id')) {
            $args['cat'] = get_query_var('cat_id');
        }

        $wp_query = new WP_Query($args);
        $posts = $wp_query->posts;

        // Prepare/format data for being displayed
        for ($i = 0; $i < count($posts); $i++) {
            $posts[$i]->post_date = new DateTime($posts[$i]->post_date);
            $posts[$i]->post_date = $posts[$i]->post_date->format("F j, Y");
            $posts[$i]->post_category = get_the_category($posts[$i]->ID);
            $posts[$i]->post_category = $posts[$i]->post_category[0]->name;
        }

**Item 1.)**

        if (get_query_var('cat_id')) {
            $args['cat'] = get_query_var('cat_id');
        }

**Item 2.)**
Do I need to format all of these things?
        // Prepare/format data for being displayed
        for ($i = 0; $i < count($posts); $i++) {
            $posts[$i]->post_date = new DateTime($posts[$i]->post_date);
            $posts[$i]->post_date = $posts[$i]->post_date->format("F j, Y");
            $posts[$i]->post_category = get_the_category($posts[$i]->ID);
            $posts[$i]->post_category = $posts[$i]->post_category[0]->name;
        }

Thanks again

JB

**Comment by barnettj7** [comment]
Here is the code I currently have in your theme.

**Page Template Testimonials**

<?php
/**
 * The main template file.
 *
 * This is the most generic template file in a WordPress theme
 * and one of the two required files for a theme (the other being style.css).
 * It is used to display a page when nothing more specific matches a query.
 * E.g., it puts together the home page when no home.php file exists.
 * Learn more: http://codex.wordpress.org/Template_Hierarchy
 *
 * @package understrap
 */

get_header(); ?>

    <?php
    if ( is_front_page() && is_home() ) {

        get_sidebar('hero'); 

        get_sidebar('statichero');
        
    } else {
    // Do nothing...or?
    }
    ?>

    <div class="wrapper" id="wrapper-index">
        
	   <div id="content" class="container">

            <div class="row">
           
    	       <div id="primary" class="<?php if ( is_active_sidebar( 'sidebar-1' ) ) : ?>col-md-8<?php else : ?>col-md-12<?php endif; ?> content-area">
                   
                     <main id="main" class="site-main" role="main">
                    
                    <?php if ( have_posts() ) : ?>

                        <?php /* Start the Loop */ ?>

                        <?php while ( have_posts() ) : the_post(); ?>

                                <?php
                                    /* Include the Post-Format-specific template for the content.
                                     * If you want to override this in a child theme, then include a file
                                     * called content-___.php (where ___ is the Post Format name) and that will be used instead.
                                     */
                                    get_template_part( 'loop-templates/content', get_post_format() );
                                ?>

                        <?php endwhile; ?>
                        
                        <?php the_posts_navigation(); ?>
                        
                    <?php else : ?>

                        <?php get_template_part( 'loop-templates/content', 'none' ); ?>
                        
                    <?php endif; ?>
                    
								<?php
                                    /* Include the Post-Format-specific template for the content.
                                     * If you want to override this in a child theme, then include a file
                                     * called content-___.php (where ___ is the Post Format name) and that will be used instead.
                                     */
                                    get_template_part( 'loop-templates/content-testimonials', get_post_format() );
                                ?>                    
                        
                    </main>
                   
    	       </div>
        
            <?php get_sidebar(); ?>

            </div>
           
       </div>
        
    </div>

<?php get_footer(); ?>


**content-tesimonials.php**

<?php
/**
 * @package understrap
 */
?>	
<?php wp_reset_query(); ?>
<?php if ( have_posts() ) : ?>
<?php /* Start the Loop */ ?>
<?php
$query = new WP_Query( array( 'post_type' => array( 'testimonials' ), 'tag__not_in' => array( 20 )) );
while( $query->have_posts() ):
$query->the_post();
?>
<div class="post-title">
	                                                            
	<?php the_title('<h1>', '</h1>'); ?>
                                                            
</div>   
                                                        
<div class="post-content">
                                                            
	<?php the_content(); ?>                               

</div>   

<?php endwhile; ?>

<?php endif; ?>  
<?php wp_reset_query(); ?>
