### ISSUE TITLE
Gulp task 'gulp-sass' error

### ISSUE THREAD

**Issue by matheusggds** [understrap/understrap-child#50]
Every Gulp Taks that use gulp-sass gives the same error:

![captura de tela 2017-04-27 as 11 29 35](https://cloud.githubusercontent.com/assets/13421113/25488226/e22cebbe-2b3c-11e7-93f0-f0c84e0c1da9.png)

I cloned/downloaded understrap and understrap-child and that error still there.

Can someone help? I cant find how fix that

**Comment by holger1411** [comment]
Please run "npm install" in your terminal first.
That will download all 3rd party dependencies and move it to the correct folder.
