### ISSUE TITLE
Safest way to use in production

### ISSUE THREAD

**Issue by ErinPo** [understrap/understrap-child#61]
I imagine it is possible that new versions of understrap can break things, even when all modifications were made in understrap-child. Or are you going to give warnings whenever this might be the case for a particular version?

What is the recommended way of dealing with updates? Should we have version specific folders like understrap060 and reference those in the child theme? This way the reference could be changed to point to a newer understrap070 for testing, and switched back quickly if needed. Of course updates to understrap-child would need to be merged in parallel...

**Comment by brunomac** [comment]
I have the same question...

any feedback?

**Comment by Thomas-A-Reinert** [comment]
hello @ErinPo  - first, sorry that noone of "team understrap" ever replied to your question for about more than a year. that´s a pity and i´ll personally like to apologize. after going through and resolving about 200 other issues i finally landed here :/

as a theme-dev i also had a hard time more than once with the problem you mentioned. currently there just is no solution, sorry. so i´ll close this issue.

but believe this is on my top-priority list once we figured out some other problems, okay?
