### ISSUE TITLE
Sass styles not showing up on theme in browser.

### ISSUE THREAD

**Issue by rw1982** [understrap/understrap-child#72]
I was able to get sass working on the theme, but only when I change it to read child-theme.css instead of child-theme.css.min in functions.php. Is there something extra I need to do to get it to read the min.css file? It picks up the styles right away with the non minified stylesheet, but it won't read any new styles at all from the minified file.

**Comment by rw1982** [comment]
Ok so it looks like it is actually compiling properly. It's just not doing it into the main child theme css file. How would I go about doing that properly? Just @import all of these into my style.css at the base of my theme? :
child-theme.css
child-theme.min.css
child-theme.min.css.map
custom-editor-style.css
custom-editor-style.min.css
custom-editor-style.min.css.map

I assume there is a "right way" since you need that style.css for the styles to actually show up on your theme. Right?

**Comment by fahaddsheikh** [comment]
Same with me

**Comment by niklasp** [comment]
Same here. gulp watch is not erroring but the styles i added to_child_theme_variables never make their way to a css file

**Comment by mcropper** [comment]
Did anyone find a work around? Im having an issue here. gulp recognises the changes and displays change to styles.min.css but changes arent updated on the front end and new classes arent in the css file or the min.css file.

**Comment by Thomas-A-Reinert** [comment]
Should be resolved by now. Closing this issue for housekeeping
