### ISSUE TITLE
Multiple Projects With UnderStrap / UnderStrap Child

### ISSUE THREAD

**Issue by axlright** [understrap/understrap-child#76]
This isn't an issue with the code as much as the strategy. We're working on getting our small dev team using UnderStrap / UnderStrap Child Theme going for multiple client projects. We'll be running a dozen or so instances at a time. Seeking some advice from others:

1) For the npm install / node_modules directory - is there a way to install that not globally but at least just once for use with multiple instances of UnderStrap / UnderStrap Child theme installs? Seems like a lot to have 17,000+ items for each install.

2) Any suggestions for a good git workflow? We want to be able to set as upstream the original holger1411 projects, but doing a single fork + clone and using submodules isn't a good solution for doing a dozen+ installs. How do other people work collaboratively on multiple UnderStrap / UnderStrap Child Themes with multiple developers via GitHub while still keeping an upstream relationship with holger1411's updates?

THANKS,

-Alex

**Comment by Thomas-A-Reinert** [comment]
you found any solution for that alex? if yes: please shed some light and close the issue. if not.. well. sorry, it seems i can help. always running a full npm install for every child here. but *hey* hd-space became cheap ;)

**Comment by axlright** [comment]
Thanks @Thomas-A-Reinert - blast from the past! 

For #1 I haven't found a solution, though this message was written quite a while ago. Of course I understand that for npm, developers need different packages and maybe versions of every package for each project. But in the case of developing ~20 versions of the same project, I sure wish I could have just one `node_modules` directory. Now I have one `node_modules` per install of UnderStrap / Understrap Child. And with each `node_modules` clocking in at ~310MB and 27,000 items, it seems like a lot to do over and over and over. But I'm not smart enough to know of a way to combine npm resources among all these projects.

I did solve #2 based on all the super duper smart people on this team.

I'll close this ticket. If anyone in this community who is also working on many instances of UnderStrap / Understrap Child has a solution for not having a full `node_modules` in every instance, let me know.

Thanks!
