### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by eberhapa** [understrap/understrap-child#83]
npm install not working with version 0.3.3.2. 

`npm WARN Invalid version: "0.3.3.2"
npm WARN understrap-child No description
npm WARN understrap-child No repository field.
npm WARN understrap-child No README data
npm WARN understrap-child No license field.
`

Changing Version to 0.3.3 in package.json fixes the problem.

**Comment by Thomas-A-Reinert** [comment]
I hope (and really guess/know to my own experience) that this has been resolved by now. Feel free to reply/reopen if needed.
