### ISSUE TITLE
How to include custom-comments.php in child theme

### ISSUE THREAD

**Issue by eberhapa** [understrap/understrap-child#90]
I want to add code into the custom-comments.php. How do I include the file correctly into the child theme?

Best,
Patrick

**Comment by rolfski** [comment]
Yeah, same question here. Can it be done by adding something in the child functions.php?

**Comment by rolfski** [comment]
I think I found a way. Copy the comments.php to your child theme. And then edit and change this:

`

	<?php
	$args = array(
	/*'comment_field' => '<p class="comment-form-comment"><label for="comment">' . _x( 'Comment', 'noun' ) . '</label><textarea id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea></p>',*/
  	'class_submit' => 'btn btn-primary btn-outline'
	);
	?>

	<?php comment_form($args); // Render comments form. ?>

`

Find other fields here:

https://premium.wpmudev.org/blog/customizing-wordpress-comment-form/

**Comment by holger1411** [comment]
Just copy and past your code into the child themes functions.php
Or copy the custom-comments.php file into the child theme folder and load it with:
`require get_template_directory() . '/icustom-comments.php';`
as external source in your functions.php

**Comment by jacksellwood** [comment]
This doesn't seem to be working. Is the comment form displayed by default in Understrap? Even after editing single.php, I can't figure this out.

**Comment by holger1411** [comment]
I think both way are good and will answere the initial question. So I´am closing this.
Feel free to re-open if necessary
