### ISSUE TITLE
I have no idea where this path leads to

### ISSUE THREAD

**Issue by onepack** [understrap/understrap-child#91]
@import "../../src/understrap/understrap/understrap";

(https://github.com/holger1411/understrap-child/blob/master/sass/assets/understrap.scss)

In Child and in the Parent theme there is no such directory structure.
It leads to errors while compiling.

**Comment by Thomas-A-Reinert** [comment]
Must have been solved by now. Never encountered that problem. Please reopen if the problem remains with latest parent/child-theme.
