### ISSUE TITLE
<!--nextpage--> Post Pagination Not Working Correctly

### ISSUE THREAD

**Issue by jrglass** [understrap/understrap-child#93]
Trying to use the default  function within the content of a post in order to split up long posts.

I have the function <?php wp_link_pages(); ?> right after <?php the_content(); ?> as shown below:

```
<?php the_content(); ?>
<!-- Post Page Pagination -->
<?php wp_link_pages( 
     array(
          'before'        => '<div class="pager clearfix"><strong class="title">Read More:</strong><ul>',
          'link_before'   => '<li>',
          'link_after'    => '</li>',
           'after'         => '</ul></div>',
     )
);
?>
```
The output is correct as you can see at the bottom of the post on our beta site: http://beta.freeskier.com/stories/more-for-the-avid-traveler-12-north-american-ski-resorts-to-add-to-your-list-this-winter

The issue is that when you click on "2" or "3" it goes to the correct page then forwards to a post where that number you clicked is within the URL.

So http://beta.freeskier.com/stories/more-for-the-avid-traveler-12-north-american-ski-resorts-to-add-to-your-list-this-winter/2 goes to http://beta.freeskier.com/stories/2-days

and... http://beta.freeskier.com/stories/more-for-the-avid-traveler-12-north-american-ski-resorts-to-add-to-your-list-this-winter/3 goes to http://beta.freeskier.com/stories/3-days-left

... and so on.

I flipped the theme back to the default 2017 theme and this issue simply doesn't exist. The pagination works as it should with /2 or /3 or /4 holding at the end of the url and showing the correct content.

Curious why this might be happening with undertrap and the use of the understrap-child theme.

Any insight in to how to fix?

**Comment by jrglass** [comment]
Any insight into this issue with the theme?

**Comment by Thomas-A-Reinert** [comment]
Does this issue still persist? We recently reworked the pagination so I guess this is solved.
Feel free to reopen.
