### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by biffwebsterjr** [understrap/understrap-child#95]
I ran `npm install` and `gulp copy-assets` and have the src directory.

But when I run `gulp watch` and save my _child_theme.scss file, I get the following error:

`Error: File to import not found or unreadable: ../../src/sass/bootstrap4/custom
       Parent style sheet: /Users/rovito/Kalabox/finetune-understrap/code/wp-content/themes/finetune/sass/assets/bootstrap4.scss
        on line 8 of sass/assets/bootstrap4.scss`

Did I skip a step or something? That file definitely doesn't exist in src.

Thanks.

**Comment by antonapua** [comment]
I've encountered the same problem. Also did npm install and copy assets. . . what I did is actually comment that line out. . .  then I imported bootstrap functions at the beginning of the boostrap4.scss. However I now have the issue Undefined variable: "$gray-light".

**Comment by antonapua** [comment]
@biffwebsterjr I actually solved my problem. 

Silly me I used the draft-child theme, I must have lost my way here. https://understrap.com/understrap-child-themes/ 

On load I jumped to the Draft Theme missing that there was the base child theme at the bottom. I've read on some of the previous issues that @holger1411 mentioned about the child theme version which led me to realize I was using the wrong child theme. Try checking what child theme you are using cause your issues are identical with mine.

**Comment by biffwebsterjr** [comment]
I'm using the theme here: https://github.com/holger1411/understrap-child

Shouldn't that be the base theme and not the draft?

**Comment by holger1411** [comment]
The Bootstrap 4 custom.scss file was used in BS4 alpha and older version, but not in the latest BS4 Beta version. 
So it seems your sass/assets/bootstrap4.scss file is from an older version.
Please compare your file with: 
https://github.com/holger1411/understrap-child/blob/master/sass/assets/bootstrap4.scss
